IlchCMS/Ilch-2.0

application/modules/forum/mappers/Post.php

Just fixed a typo in application/modules/forum/mappers/Post.php in the name of getAllPostsByUserId()

Fix typo in function-name

---

application/modules/admin/views/admin/layouts/search.php

Add a message regarding no layouts found instead of failing with
"Invalid argument supplied for foreach()".
The translation for "noLayoutsAvailable" is missing in this pull-request. It ended up being part of a not yet send pull request for ticket 249.
http://redmine.ilch2.de/issues/249

Add message regarding no layouts available

---

application/libraries/Ilch/View.php
application/modules/events/controllers/Index.php

Fix the image condition and don't overwrite the error-message.
Previously the "failedFilesize" or "failedFiletypes"-errors were likely
never visible.

Fix image condition and error-message

---

application/modules/user/config/config.php
application/modules/user/controllers/admin/ProfileFields.php
application/modules/user/mappers/ProfileFields.php
application/modules/user/models/ProfileField.php
application/modules/user/views/admin/profilefields/index.php

Add support to resort profile-fields.
Now the administrator can resort the profile-fields by drag and drop.
Further display categories with a bold font in the admincenter so a category can be distinguished from a normal profile-field.

Add support to resort profilefields.

---

application/modules/page/mappers/Page.php

This fixes the following issue:
PHP Warning:  Invalid argument supplied for foreach() in
application\modules\admin\views\admin\settings\index.php on line 11
This one occured when there was no page. getPageList() returned 'null' in this case, which lead to the issue above when passed as argument for foreach().

Fix invalid argument supplied for foreach()

---

application/modules/rule/controllers/Index.php
application/modules/rule/controllers/admin/Index.php
application/modules/rule/mappers/Rule.php
application/modules/rule/views/admin/index/index.php

Fixed the issue found by NDHellfire.
> Catchable fatal error: Argument 1 passed to Modules\Rule\Mappers\Rule::save() must be an instance of Modules\Rule\Models\Entry, instance of Modules\Rule\Models\Rule given, called in application\modules\rule\controllers\admin\Index.php on line 99 and defined in application\modules\rule\mappers\Rule.php on line 110
Thread related to this issue:
http://www.ilch.de/forum-showposts-53407.html
Further finished the started work of renaming "entry" or
"entries" to a more specific name like "rule" or "rules".

Fix fatal-error in rule-module

---

application/libraries/Ilch/Functions.php
application/modules/user/plugins/BeforeControllerLoad.php

Use hash_equals() instead of ilch_function_hash_equals() as the minimum
supported PHP version for Ilch 2 is now 5.6.
ilch_function_hash_equals() was used because hash_equals() is only
available with PHP 5.6 and newer.
Remove ilch_function_hash_equals() as it is no longer needed.
This is basically a revert of https://github.com/IlchCMS/Ilch-2.0/commit/7f27530f5cdb4cf3a050ecb0b60852da6714de98

Use hash_equals()

---

application/libraries/Ilch/Layout/Helper/GetMenu.php
application/libraries/Ilch/Layout/Helper/Menu/Model.php

z.B. sinnvoll für die bootstrap navbar, die keine Verschachtelungen unterstützt. Ist im Layout bei dem Menü allow-nesting auf false, werden die Verschachtelungen nicht übernommen, sondern die Links ganz normal untereinander angezeigt.

Menu: Adds allow-nesting option

---

application/modules/admin/controllers/admin/Index.php
application/modules/user/mappers/User.php

I didn't saw the getUserList(), which can be used to get the same
result. Therefore getNotConfirmedUsers() is not needed.

Remove getNotConfirmedUsers()

---

application/libraries/Ilch/Controller/Base.php
application/libraries/Ilch/Layout/Base.php

Szenario:
- Modul A ruft addMessage auf, leitet weiter auf Modul B.
- Übersetzung von addMessage wird in den Übersetzungen von Modul B gesucht
- Modul B besitzt die Übersetzung nicht, da es die Message von Modul A gar nicht kennt.
-> keine Übersetzung
Mit der Änderung ist jedes Modul für seine eigenen addMessage Aufrufe zuständig, vorher das, bei dem die Message letztlich angezeigt wurde.

Shifts addMessage translation

---

application/modules/admin/mappers/Module.php

Oder brauchen wir irgendwo mehr als die aktuelle Locale vom Modul?
Vorher wurden ja alle Locales per addContent() hinzugefügt, war das notwendig?
Wenn ja, muss man hier halt noch ein paar Kleinigkeiten ändern.
So werden die Module jetzt jedenfalls nach dem Anzeigenamen sortiert und nicht mehr nach dem Key.

Admin/Modules: Sorts by localized module name

---

application/modules/article/views/admin/index/treat.php
application/modules/article/views/admin/settings/index.php
application/modules/awards/views/admin/index/treat.php
application/modules/guestbook/views/index/newentry.php
application/modules/jobs/views/admin/index/treat.php
application/modules/jobs/views/index/show.php
application/modules/link/views/admin/index/treatCat.php
application/modules/link/views/admin/index/treatLink.php
application/modules/partner/views/admin/index/treat.php
application/modules/partner/views/index/index.php
application/modules/rule/views/admin/index/treat.php

https://github.com/IlchCMS/Ilch-2.0/pull/201/commits/9a19257bc554b1437c5d596bc65f7c412c5a5794
After the changes in this commit "errors" is no longer null in case of
no errors. Now it is an empty array. Adjust the code according to it.

Fix validation-class view-code

---

application/modules/install/controllers/Index.php
application/modules/install/views/index/systemcheck.php

Functions of mbstring are currently used in the validator and password_compat.
Zip-extension is used in the transfer-class.
http://redmine.ilch2.de/issues/335

Check if mbstring- and zip-extension are loaded

---

application/modules/comment/translations/de.php
application/modules/comment/translations/en.php
application/modules/comment/views/admin/index/index.php

The comment-id, which is the auto-incrementing primary key in the
database is of no use to the user. Therefore no need to display it.

Hide the comment-id

---

application/modules/article/controllers/admin/Settings.php

PHP Warning:  in_array() expects parameter 2 to be array, null given in
application\modules\article\views\admin\settings\index.php on line 14

Add missing errorFields

---

application/libraries/Ilch/Translations/de.php
application/libraries/Ilch/Translations/en.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php

Added the general translation "saveSuccess" to the general translation-file and removed it from the language-files of the modules.

Move saveSuccess-translation

---

application/modules/smilies/controllers/admin/Index.php

Use unique-validator to prevent the user from giving a smilie a name, which is already in use.
Further when uploading a new smilie an index is added to its name. The index gets incremented as long as the resulting name would be still a already used one.
http://redmine.ilch2.de/issues/339

Avoid duplicated smilie-names (Ticket 339)

---

application/libraries/Ilch/Functions.php
application/modules/admin/controllers/admin/Index.php
application/modules/admin/controllers/admin/Settings.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/index/index.php

On basic version-querys or list of modules/layouts timeout after 20
seconds.
For downloading updates/modules/layouts a timeout is not set for now.
Set the timeout for connecting to the update-server to 10 seconds. If
the server doesn't respond after 10 seconds then just give up.
These timeouts shoud avoid the case where we reach the max_execution_time of php and therefore would fail with a fatal error.

Set CURLOPT_TIMEOUT and CURLOPT_CONNECTTIMEOUT

---

application/modules/admin/views/admin/infos/phpextensions.php

Remove the "PHP-extension" text infront of the extension name as it is
not needed in a list of needed PHP-extensions.

Remove redundant text

---

application/libraries/Ilch/Controller/Base.php
application/libraries/Ilch/Layout/Base.php
application/libraries/Ilch/Redirect.php
application/libraries/Ilch/Request.php
application/libraries/Ilch/View.php
application/modules/guestbook/controllers/Index.php
application/modules/guestbook/models/Entry.php
application/modules/guestbook/views/index/newentry.php

`$this->redirect([...])` sollte weiterhin so funktionieren, wie vorher (Stichprobenartig ausprobiert).
`$this->redirect()` gibt nun eine Instanz von \Ilch\Redirect zurück.
```php
$this->redirect()
->withMessage($translationKey, 'success')
->withInput($dataArray = $_POST) // Leer für $_POST
->withErrors(\Ilch\Validation\ErrorBag $errorBag) // \Ilch\Validation::getErrorBag()
->to(['controller' => 'x', 'action' => 'y']);
```
Im View dann durch die hinzugefügten helper methods
```php
// Zugriff auf die ErrorBag-Instanz
$this->validation();
// Prüfen, ob Fehler der Validation existieren
$this->validation()->hasErrors();
// Array mit Fehlermeldungen
$this->validation()->getErrorMessages();
// Auf Fehler bei einem einzelnen Formularfeld prüèen
$this->validation()->hasError('field');
// Auf die …
```

Adds Redirect class

---

application/modules/newsletter/controllers/admin/Receiver.php
application/modules/newsletter/mappers/Newsletter.php
application/modules/newsletter/views/admin/receiver/index.php

Subscribers/Receivers can now be deleted in the admincenter.
Added deleteSubscriberBySelector() to avoid adding an email address as
parameter to the deleteAction-url. Instead of an email-address the
selector is now added as parameter.
Email addresses or other potential sensible data should not be added as
parameters in urls to avoid them being leaked in browser histories or to
proxies.
http://redmine.ilch2.de/issues/375

Add deleting of subscribers

---

application/modules/user/controllers/admin/Index.php
application/modules/user/mappers/AuthToken.php

Delete all auth token of a user being deleted. There might be more than
one auth token for a user if he logged in on different browsers or
devices.
Fix a comment.

Delete all auth token of a user being deleted

---

application/modules/admin/controllers/admin/Index.php
application/modules/admin/controllers/admin/Modules.php
application/modules/admin/layouts/index.php
application/modules/admin/views/admin/index/index.php
application/modules/admin/views/admin/modules/index.php
application/modules/admin/views/admin/modules/search.php

Use the version number from the database if possible instead of the VERSION constante, which is now only used in the install module.

Use version number from database if possible

---

application/modules/install/controllers/Index.php
application/modules/install/translations/de.php
application/modules/install/views/index/systemcheck.php

Check if the mysqli extension is loaded.
> Depending on the version of PHP, there are either two or three PHP APIs for accessing the MySQL database. PHP 5 users can choose between the deprecated mysql extension, mysqli, or PDO_MySQL. PHP 7 removes the mysql extension, leaving only the latter two options.
> This extension is deprecated as of PHP 5.5.0, and has been removed as of PHP 7.0.0. Instead, either the mysqli or PDO_MySQL extension should be used.
http://php.net/manual/en/intro.mysql.php 
http://php.net/manual/en/mysql.php

Check if the mysqli extension is loaded

---

static/js/ilch.js

Uncaught The editor instance "ck_1" is already attached to the provided
element.
http://redmine.ilch2.de/issues/413

Destroy instance if it already exists

---

application/modules/contact/controllers/Index.php
application/modules/jobs/controllers/Index.php
application/modules/newsletter/controllers/admin/Index.php
application/modules/user/controllers/Login.php
application/modules/user/controllers/Mail.php
application/modules/user/controllers/Regist.php
application/modules/user/controllers/admin/Index.php

> Pflichtangabe nach RFC 5322. Eine oder mehrere durch Kommata getrennte E-Mail-Adressen, die den oder die Absender einer E-Mail bezeichnen. Die meisten E-Mail-Clients unterstützen nur einen einzelnen Absender.
https://de.wikipedia.org/wiki/Header_(E-Mail)#From:_Absender
Add -t and remove space between -f and the mail-adress
-t: Extract  recipients from message headers. These are added to any
recipients specified on the command line.

Add standardMail to From-MailHeader

---

application/modules/admin/views/admin/infos/logs.php
application/modules/teams/controllers/admin/Index.php
application/modules/teams/translations/de.php
application/modules/teams/translations/en.php

- Forbid leader and co-leader to be identical
- Add saveSuccess-message
- Add class btn to "clear log"-button

Forbid leader and co-leader to be identical

---

application/modules/admin/config/config.php
application/modules/awards/config/config.php
application/modules/awards/controllers/admin/Index.php
application/modules/events/config/config.php
application/modules/forum/config/config.php
application/modules/gallery/config/config.php
application/modules/guestbook/config/config.php
application/modules/jobs/config/config.php
application/modules/jobs/controllers/admin/Index.php
application/modules/partner/config/config.php
application/modules/privacy/config/config.php
application/modules/user/config/config.php

"For optimum storage, you should try to use the most precise type in all
cases."
https://dev.mysql.com/doc/refman/5.7/en/choosing-types.html
awards
[prefix]_awards
Possible values: 1 or 2
`typ` TINYINT(1) NOT NULL,
events
[prefix]_events
Possible values: 0 or 1
`show` TINYINT(1) NOT NULL,
[prefix]_events_entrants
Possible values: 1 or 2
`status` TINYINT(1) NOT NULL
forum
[prefix]_forum_items
Possible values: 0 or 1
`type` TINYINT(1) NOT NULL,
[prefix]_forum_topics
`type` TINYINT(1) NOT NULL DEFAULT 0,
Possible values: 0 or 1
`status` TINYINT(1) NOT NULL DEFAULT 0,
Possible values: 0 or 1
gallery
[prefix]_gallery_items
Possible values: 0 or 1
`type` TINYINT(1) NOT NULL,
guestbook
[prefix]_gbook
Possible values: 0 or 1
`setfree` TINYINT(1) NOT NULL DEFAULT 0,
jobs
[prefix]_jobs
Possible …

Try to use the most precise type (int to tinyint)

---

application/libraries/Ilch/Validation.php
application/libraries/Ilch/Validation/Validators/Exists.php

Bitte mal noch testen.
Hab es testhalber mal beim War-Modul eingefügt:
```php
'warEnemy' => 'required',
'warGroup' => 'required',
```
zu
```php
'warEnemy' => 'required|exists:war_enemy',
'warGroup' => 'required|exists:war_groups',
```
**Anwendung:**
```
exists:tableName[,column, another_column, another_column_value, ...]
```
**Notwendig:**
**_tableName_:** Tabellenname ohne Prefix
**Optional:**
**_column_:** Standardmäßig wird hier die `id` column geprüft (d.h. `id` muss dem Wert des Formularfeldes entsprechen).
**_another_column_ und _another_column_value_:** Hier können nun beliebig viele WHERE-Conditions hinzugefügt werden. Alle Bedingungen werden mit AND verknüpft. Für komplexere Sachverhalte muss ein eigener Validator erstellt werden.
_Beispiele:_ 
`email,example@email.com` …

Exists validator

---

application/modules/install/controllers/Index.php
application/modules/install/translations/de.php
application/modules/install/translations/en.php
application/modules/install/views/index/ajaxconfig.php

**Example:**
Module A depends on module B.
If module A gets selected then select module B, too.
It is impossible to deselect module B if module A is still selected.
Currently the detailed dependency (like the version of the war-module must be >=,1.0) is not checked.

Check dependencies in install-module

---

application/modules/war/views/index/show.php

Dadurch das die Ausgabe über den BBCode parser läuft (im Admin aber der normale ckEditor genutzt wird), entstehen 2 Zeilenumbrüche zuviel in jedem p-tag.

Warmodul: Fehler durch BBCode parsing

---

application/libraries/Ilch/Page.php
application/libraries/Ilch/Translator.php

The goal is to enable layouts to have own language files. These translations should not override other translations (like from modules). They are stored and handled separately.
This is based on a previous try:
https://www.ilch.de/forum-showposts-55126.html#397137
Tested with vagrant running on a windows host.
Debian 10
PHP 7.3.11
Apache 2.4.38
MariaDB 10.3.18

Add handling of language files in layouts

---

application/libraries/Ilch/Translator.php

Previously if a layout would have used translations the translations of the module/ilch would have been used.
This should restore the previous behaviour in case the translation in the layout is missing.
In addition to this add the recommendation of Mairu regarding DIRECTORY_SEPARATOR
https://github.com/IlchCMS/Ilch-2.0/pull/466#discussion_r381369304

Fix: Add fallback to other translations

---

application/libraries/Ilch/Mail.php
application/modules/contact/controllers/Index.php
application/modules/contact/controllers/admin/Index.php
application/modules/contact/layouts/mail/contact.php
application/modules/contact/translations/de.php
application/modules/contact/translations/en.php

- Add replyTo to mail class
- Usage in the contact module to allow a direct reply to the email.
- Added the mail body to the mailto URI.
It was impossible to directly reply to an email received over the contact module. Further the mailto URI, which is added to the email, lacked the email body.
https://www.ilch.de/forum-showposts-55978.html

Add replyTo to mail class and usage in contact module

---

application/libraries/Ilch/Controller/Frontend.php
application/libraries/Ilch/Design/Base.php
application/libraries/Ilch/Layout/Frontend.php
application/libraries/Ilch/Translator.php
application/modules/admin/config/config.php
application/modules/admin/controllers/admin/Layouts.php
application/modules/admin/mappers/LayoutAdvSettings.php
application/modules/admin/models/Layout.php
application/modules/admin/models/LayoutAdvSettings.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/layouts/advsettings.php
application/modules/admin/views/admin/layouts/advsettingsshow.php
application/modules/admin/views/admin/layouts/index.php
tests/modules/admin/_files/mysql_database.yml
tests/modules/admin/mappers/LayoutAdvSettingsTest.php

This is still work in progress. The "design" of the settings is not polished.
The goal is that layouts can specify settings in their config.php and Ilch provides a central place for the administrator to change those settings. Previously a layout that wanted to provide settings would have to come with an module, which handles these. This should no longer be needed with these changes.
Layouts can use the set values for the settings like this:
`$this->getLayoutSetting('title')`

Advanced layout settings

---

application/modules/admin/controllers/admin/Index.php
application/modules/admin/controllers/admin/Layouts.php
application/modules/admin/mappers/Module.php
application/modules/admin/models/Layout.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/layouts/index.php
application/modules/admin/views/admin/layouts/search.php
application/modules/admin/views/admin/layouts/show.php

This is still work in progress and a few cases need testing and further work:
A layout can now specify the minimum needed Ilch version and further it is now checked if the module associated with the layout is installed.
This is needed as older versions of Ilch obviously don't support the advanced layout settings and language files in layouts.

Add some layout requirements

---

application/libraries/Ilch/Controller/Base.php
application/libraries/Ilch/Database/Mysql.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/user/controllers/Regist.php
application/modules/user/views/regist/finish.php
application/modules/user/views/regist/index.php

Fixes #501
The previous solution didn't worked with a page as startpage instead of a module.
https://github.com/IlchCMS/Ilch-2.0/pull/524
The previous solution didn't worked with a page as startpage instead of a module.
See comments in previous pull request:
https://github.com/IlchCMS/Ilch-2.0/pull/524
Make use of the normal code path to get back to the configured startpage.
Fixes #501

Ticket 501: Back to startpage after registration

---

.travis.yml
composer.json
composer.lock

Use sminnee/phpunit-mock-objects, which is a fork of the deprecated phpunit-mock-objects. This hopefully allows to run unit tests under PHP 8 until it is possible to update to PHPUnit 9 or newer.
Using that fork has the drawback of using an even older and forked PHPUnit.
https://github.com/sminnee/phpunit-mock-objects
https://github.com/sminnee/phpunit
> PHPUnit 9.2.5 requires PHP 7.3 or newer.
Ilch should consider dropping support for PHP 7.0, 7.1 and probably 7.2 in June 2022 or earlier if unit tests don't run under the latest stable version of PHP.
See
[Function ReflectionParameter::isArray() is deprecated](https://github.com/IlchCMS/Ilch-2.0/issues/475)
[Drop support for PHP 7.0/7.1](https://github.com/IlchCMS/Ilch-2.0/issues/482)
```
composer update
Loading composer repositories with …
```

Use sminnee/phpunit-mock-objects

---

application/modules/gallery/boxes/Pictureofx.php
application/modules/gallery/config/config.php
application/modules/gallery/mappers/Gallery.php
application/modules/gallery/mappers/Image.php

Fix recently introduced errors in the gallery module and some older ones found while testing.
- Fixed 'Undefined array key "imgid"'
- Fixed 'foreach() argument must be of type array|object, null given' in settings
- PictureOfX previously didn't use pictures of all selected galleries.
Fixes #541

Fix a few errors in the gallery module

---

application/modules/article/controllers/admin/Index.php
application/modules/article/controllers/admin/Templates.php
application/modules/article/mappers/Template.php
application/modules/article/views/admin/index/treat.php
application/modules/article/views/admin/templates/index.php
application/modules/article/views/admin/templates/treat.php

The article template feature doesn't need to take multi language into account. This was broken to begin with. Simplify the template feature.
These changes where laying around from earlier work. I pulled this out of a previous pull request to send it in separately.

Simplify the article template feature

---

application/libraries/Ilch/Database/Mysql/Select.php
tests/libraries/ilch/Database/Mysql/SelectTest.php

Add deprecation warnings and adjust the QueryBuilder so that it converts those to a separate ORDER BY.
Further adjusted the existing unit test and added a unit test for the case group() is used with direction and order() too (order() should not "overwrite" the ORDER BY of the GROUP BY).
> "GROUP BY" with ASC or DESC is deprecated since MySQL 5.7 and support got removed with MySQL 8.0.13 released on October 22nd of 2018.
[QueryBuilder: GROUP BY ASC or DESC is no longer supported](https://github.com/IlchCMS/Ilch-2.0/issues/534)
The documentation for the QueryBuilder needs to be updated to show that providing a sortorder to group() is no longer supported.

Deprecate GROUP BY ASC or DESC

---

application/libraries/Ilch/Database/Mysql/Insert.php
application/modules/guestbook/config/config.php
application/modules/user/mappers/GalleryImage.php
application/modules/vote/config/config.php
tests/libraries/ilch/Database/Mysql/InsertTest.php

- Added support for inserting multiple rows
- Added a few unit tests
- Fixed guestbook updating description of wrong module
Fixes #535 
What do you think of this change and the syntax for the QueryBuilder? Please review.
The syntax should be:
> $this->db()->insert('Test')
>     ->columns(['super', 'next'])
>     ->values([['data', 'fieldData'], ['data2', 'fieldData2'], ['data3', 'fieldData3']]);
>     ->execute();
As of now not tested outside the unit tests for the query builder.

Issue 535: add support for inserting multiple rows

---

application/modules/user/config/config.php
application/modules/user/controllers/admin/Profilefields.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php
application/modules/user/views/admin/profilefields/treat.php
application/modules/user/views/index/index.php

- Add the icon picker from the history module so an admin has more choice than just the eight ones previously.
- This also fixes the previously not working preview of the available icons (see the screenshot).
- Convert the known icons currently in the database to the new format. This doesn't change different icons that where manually entered in the database. These will probably break tho as I removed the "fa " prefix in the frontend.
- Fixed menu being labeled wrong (showed edit field when it is adding).
See https://github.com/IlchCMS/Ilch-2.0/issues/484
Fixes #484

Issue 484/bigger choice of icons for profile fields

---

application/libraries/Ilch/Database/Mysql/Select.php
application/modules/contact/translations/de.php
application/modules/contact/translations/en.php
application/modules/user/config/config.php
application/modules/user/controllers/Panel.php
application/modules/user/mappers/Dialog.php

- When user A got a message from user B, but just deletes the chat or reads it in the preview before deleting it, then that message was still shown as unread. Mark all messages as read when deleting the chat.
- When user A deleted a chat and user B writes him again after it, then a new message was shown, but user A was unable to read it.
- When user A received multiple messages from user B while offline or in another tab before returning then updateRead() got called too often - basically marking every single messages as read one by one. This caused unnecessary calls to the database.
- Restore dialogs/chats with unread messages with the ilch update

Fix a few issues in the chat

---

application/modules/checkoutbasic/config/config.php
application/modules/checkoutbasic/views/admin/index/settings.php
tests/libraries/ilch/Database/Mysql/SelectTest.php

Just adding a small unit test for two or more joins. Before the commit below a second (or more) join started with two spaces.
https://github.com/IlchCMS/Ilch-2.0/commit/c781cc0c0e0f23bab639b176bf80b5bb79f1a2ea
Before and after the fix:
```
Before:
SELECT * FROM `[prefix]_Test` AS `a` INNER JOIN `[prefix]_Table2` AS `b` ON `a`.`field1` = `b`.`field2`  INNER JOIN `[prefix]_Table3` AS `c` ON `a`.`field1` = `c`.`field2`;
After:
SELECT * FROM `[prefix]_Test` AS `a` INNER JOIN `[prefix]_Table2` AS `b` ON `a`.`field1` = `b`.`field2` INNER JOIN `[prefix]_Table3` AS `c` ON `a`.`field1` = `c`.`field2`;
```

Add a unit test for two joins

---

application/libraries/Ilch/Database/Mysql/Insert.php
application/modules/away/config/config.php
application/modules/away/controllers/Index.php
application/modules/away/controllers/admin/Index.php
application/modules/away/controllers/admin/Settings.php
application/modules/away/mappers/Away.php
application/modules/away/mappers/Groups.php
application/modules/away/translations/de.php
application/modules/away/translations/en.php
application/modules/away/views/admin/index/index.php
application/modules/away/views/admin/settings/index.php
application/modules/away/views/aways/index.php
application/modules/away/views/index/index.php
tests/libraries/ilch/Database/Mysql/InsertTest.php
tests/modules/away/_files/mysql_database.yml
tests/modules/away/mappers/GroupsTest.php

- Added optional notifications of administrators and/or user groups in case of new entries or changed status of entries in the away list. By default notifications for administrators are enabled (notification in the admincenter).
- Added unit tests for the new "groups" mapper
- QueryBuilder: Inserting multiple rows of just one column failed.
- QueryBuilder: Added a few more unit tests.
Fixes #459 
ToDo:
- ~~More notifications?~~
Asking for feedback.

Issue 459: Add notifications to away module

---

application/modules/user/config/config.php

In der Mitgliederliste im Frontend werden die Benutzergruppen mit angezeigt in welcher die User sind. 
Bei Bedarf kann die Ansicht in den Settings  ein -/ ausgeschaltet werden.
Ein User im Forum hatte sich dieses gewünscht :)

Benutzergruppen im Frontend anzeigen

---

application/libraries/Ilch/Validation/Validators/Exists.php

Exists-Validator invert hinzugefügt

Exists-Validator invert hinzugefügt

---

development/vagrant/Vagrantfile
development/vagrant/scripts/install.sh
development/vagrant/scripts/install_mailhog.sh
tests/README.md
tests/libraries/ilch/RouterTest.php

- Update Vagrant to Debian 11.
- assertMatchesRegularExpression() is not available in older versions of PHPUnit. Vagrant and GitHub Actions use PHPUnit in version 5.7.27
- Wrong username and password in readme for running unit tests
> 1) Ilch\RouterTest::testDefaultRegexpPattern
> Error: Call to undefined method Ilch\RouterTest::assertMatchesRegularExpression()
>
> /vagrant/tests/libraries/ilch/RouterTest.php:40
> /vagrant/vendor/sminnee/phpunit/phpunit:51
@hhunderter 
Wie führst du Unittests aus? Nutzt du eine neuere Version von PHPUnit?

Update vagrant and fix unit test

---

.github/workflows/ci.yaml
application/libraries/Ilch/Functions.php
application/modules/install/controllers/Index.php
application/modules/install/views/index/systemcheck.php
composer.json
composer.lock
index.php
tests/libraries/ilch/RouterTest.php

Remove support for older versions than PHP 7.3. Ilch then supports PHP 7.3 - PHP 8.1. Run unit tests for the supported PHP versions.
- Minimum supported PHP version would be 7.3.
- Workaround for samesite attribute for older versions of PHP than 7.3 is no longer needed.
- Run unit tests for PHP 7.3 to 8.1
- Update various components.
-- jQuery File Upload auf Version 10.32.0 aktualisiert.
-- CKEditor auf Version 4.20 aktualisiert.
-- JQuery auf Version 3.6 aktualisiert.
-- HTMLPurifier auf Version 4.16 aktualisiert.
-- PHPMailer auf Version 6.6.5 aktualisiert.
-- FontAwesome auf Version 5.15.4 aktualisiert.
-- PHPUnit auf Version 9.5.26 aktualisiert.
-- ...
- sminnee/phpunit is no longer needed (https://github.com/IlchCMS/Ilch-2.0/pull/529) and it looked like it would be hard to run unit …

Update github actions and composer

---

.gitattributes
.github/workflows/build.yaml

* add GitHub action
* that creates a Ilch2 archive (on the master branch, should be possible to trigger manually for other branches)
* There is a limitation when downloading the archive from GitHub actions page, that it is inside a zip folder -> https://github.com/actions/upload-artifact#zipped-artifact-downloads
* also artifacts will be deleted after 90 days
* create a release draft when a tag in the form v1.2.3 or v1.2.3-alpha-1 is created
* archive is attached to that release draft -> example: https://github.com/IlchCMS/Ilch-2.0/releases/tag/untagged-3ed336c0f196dc4998e1
Closes #592

Build pipeline

---

application/libraries/Ilch/Comments.php
application/libraries/Ilch/Mail.php
application/modules/article/mappers/Category.php
application/modules/article/views/admin/templates/treat.php
application/modules/forum/config/config.php
application/modules/forum/controllers/Rememberedposts.php
application/modules/linkus/views/admin/index/index.php
tests/modules/article/_files/categories_table.yml
tests/modules/article/mappers/ArticleTest.php
tests/modules/article/mappers/CategoryTest.php
tests/modules/article/mappers/TemplateTest.php

- Fix "Call to a member function getId() on null" in the forum module
- Fix the usage of reset() on null instead of an array in the category mapper of the article module
- Add some unit tests for the category mapper
- Add return values to the function delete() and save() in the category mapper (return id or affected rows).
- Fix wrong argument names in addStringAttachment()
- Other small fixes

Various fixes

---

development/README.md
development/composer.json
development/composer.lock
phpcs.xml

- Set php platform to PHP 7.3.
- Use newest possible versions of "squizlabs/php_codesniffer" and "friendsofphp/php-cs-fixer"
- Added "phpcompatibility/php-compatibility"
- Removed "sjparkinson/static-review" as it is deprecated and complicated the dependencies in composer.
- It is no longer needed to exclude password-compat as it is no longer a part of ilch.
- Check against the coding standard PSR12 as PSR2 is deprecated.
- Updated the readme
**"phpcompatibility/php-compatibility"**
This is a set of sniffs for [PHP CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) that checks for PHP cross-version compatibility. It will allow you to analyse your code for compatibility with higher and lower versions of PHP.
I was considering the suggested replacement for …

Update developer tools

---

application/libraries/Ilch/Layout/Helper/AdminHmenu/Model.php
application/libraries/Ilch/Layout/Helper/Menu/Model.php
application/modules/admin/models/Module.php

Installation von 2.1.45 unter PHP 8.2 hatte einige Fehler die hiermit gefixt werden.
```
Deprecated: Creation of dynamic property Ilch\Layout\Helper\Menu\Model::$layout is deprecated in application\libraries\Ilch\Layout\Helper\Menu\Model.php on line 52
Deprecated: Creation of dynamic property Modules\Admin\Models\Module::$content is deprecated in application\modules\admin\models\Module.php on line 213
Deprecated: Creation of dynamic property Ilch\Layout\Helper\AdminHmenu\Model::$layout is deprecated in application\libraries\Ilch\Layout\Helper\AdminHmenu\Model.php on line 23
```

Code Fixes

---

application/modules/forum/config/config.php
application/modules/forum/controllers/Showposts.php
application/modules/forum/translations/de.php
application/modules/forum/translations/en.php
application/modules/forum/views/showposts/index.php

Add confirmation prompt to delete action. Further use a token for the delete action.
Fixes #500
Fixes #620

Add confirmation prompt to delete action

---

application/modules/admin/layouts/index.php
application/modules/admin/views/admin/layouts/settings.php
application/modules/article/views/admin/index/treat.php
application/modules/article/views/admin/templates/treat.php
application/modules/awards/config/config.php
application/modules/awards/views/admin/index/treat.php
application/modules/downloads/config/config.php
application/modules/downloads/views/admin/file/treatfile.php
application/modules/link/config/config.php
application/modules/link/views/admin/index/treatLink.php
application/modules/linkus/config/config.php
application/modules/linkus/views/admin/index/treat.php
application/modules/partner/config/config.php
application/modules/partner/views/admin/index/treat.php
application/modules/user/views/profil/index.php
application/modules/war/config/config.php
application/modules/war/views/admin/enemy/treat.php
application/modules/war/views/admin/group/treat.php

Looks like a simple conversion from "fa" to "fas" or "fa-solid" would break the icon.
Change it to FontAwesome v6 style and use the new name ("fa-regular fa-image").

Change fa fa-picture-o to fa-regular fa-image

---

application/modules/calendar/mappers/Calendar.php

Setting up a recurring event for e.g. every monday until a specific date didn't work previously.

Fix next weekday feature

---

application/modules/calendar/controllers/admin/Index.php
application/modules/calendar/views/admin/index/treat.php

Suggest an repeat until date and require it with recurring events.
For daily 1 month later.
For weekly and a specific weekday 6 months later.
For monthly 1 year later.
For quarterly and yearly 5 years later.
The used JavaScript function padStart() is not supported by Internet Explorer. IE is no longer supported by Microsoft.

Calendar: Suggest an repeat until date

---

application/libraries/Ilch/Transfer.php

Fix case mismatch in function name.
Class names as well as function/method names are case-insensitive, but it is considered good practice to use them as they appear in their declaration.

Fix case mismatch in function name

---

composer.lock

> A cross-site scripting vulnerability has been discovered affecting Iframe Dialog and Media Embed plugins.
https://github.com/ckeditor/ckeditor4/blob/master/CHANGES.md

Update to CKEditor 4.21.0

---

application/modules/away/config/config.php
application/modules/away/controllers/Index.php
application/modules/away/controllers/admin/Index.php
application/modules/away/controllers/admin/Settings.php
application/modules/away/views/admin/index/index.php
application/modules/away/views/index/index.php

- Fix deprecation warning "trim(): Passing null to parameter of type string is deprecated"
- Convert FontAwesome style classes to FontAwesome 6

Fixes away module

---

application/libraries/Ilch/Validation/Validators/Integer.php
application/libraries/Ilch/Validation/Validators/Same.php
application/libraries/Ilch/Validation/Validators/Unique.php
tests/libraries/ilch/Validation/Validators/CaptchaTest.php
tests/libraries/ilch/Validation/Validators/DateTest.php
tests/libraries/ilch/Validation/Validators/EmailTest.php
tests/libraries/ilch/Validation/Validators/ExistsTest.php
tests/libraries/ilch/Validation/Validators/IntegerTest.php
tests/libraries/ilch/Validation/Validators/MaxTest.php
tests/libraries/ilch/Validation/Validators/MinTest.php
tests/libraries/ilch/Validation/Validators/NumericTest.php
tests/libraries/ilch/Validation/Validators/RequiredTest.php
tests/libraries/ilch/Validation/Validators/SameTest.php
tests/libraries/ilch/Validation/Validators/SizeTest.php
tests/libraries/ilch/Validation/Validators/UniqueTest.php
tests/libraries/ilch/Validation/Validators/UrlTest.php
tests/libraries/ilch/Validation/_files/mysql_database.yml
tests/libraries/ilch/ValidationTest.php
tests/modules/admin/mappers/LayoutAdvSettingsTest.php

- Write unit tests for most validators.
- Fixed $invertErrorKey in integer, same and unique validator (**therefore a different error key is now returned!**)
Fixes #661

Add unit tests for more validators

---

application/libraries/Captcha/Captcha.php

- Updated to version 0.3.2
- Fixed "Content-Type"
- Fixed "PHP Deprecated: Implicit conversion from float to int loses precision"
- Fixed "PHP Deprecated: Creation of dynamic property is deprecated"

Fixed deprecation warnings in Captcha class

---

tests/libraries/ilch/ValidationTest.php

Update unit test of the numeric validator, because of the changed invert error key.

Update unit test of the numeric validator

---

application/libraries/Ilch/Comments.php
application/modules/admin/config/config.php
application/modules/comment/config/config.php
application/modules/comment/controllers/admin/Index.php
application/modules/comment/controllers/admin/Settings.php
application/modules/comment/mappers/Comment.php
application/modules/comment/translations/de.php
application/modules/comment/translations/en.php
application/modules/comment/views/admin/settings/index.php

- Add a flood protection for comments. This prevents a user (which might be a bot) from creating a lot of comments in a short time. It is enabled by default with a value of 10 seconds.
- FontAwesome 6 adjustments
- Code Style

Add flood protection for comments

---

application/modules/admin/config/config.php
composer.lock

Update jQuery to version 3.7.0.

Update to jQuery 3.7.0

---

application/libraries/Ilch/Database/Mysql/Select.php
tests/libraries/ilch/Database/Mysql/InsertTest.php
tests/libraries/ilch/Database/Mysql/SelectTest.php
tests/libraries/ilch/Database/Mysql/UpdateTest.php

- Support functions in group by
- Remove support for a sortorder in a group by. This is deprecated since MySQL 5.7 and removed with MySQL 8.0.13
- Remove usage of deprecated setMethods() of PHPUnit.
- Further some code style fixes.
Fixes #534 
Fixes #536

QueryBuilder: Support functions in group by and remove sortorder

---

development/composer.json
development/composer.lock

Use the developer branch for php-compatibility.
9.3.5 was horrible out of date as it was released in December 2019.

Use the developer branch for php-compatibility

---

composer.lock

Update mysqldump-php to v2.12
> move start transaction code to a global level
fixes inconsistent database dumps

Update mysqldump-php to v2.12

---

application/modules/awards/config/config.php
application/modules/awards/controllers/Index.php
application/modules/awards/controllers/admin/Index.php
application/modules/awards/mappers/Awards.php
application/modules/awards/mappers/Recipients.php
application/modules/awards/models/Awards.php
application/modules/awards/models/Recipient.php
application/modules/awards/static/css/awards.css
application/modules/awards/translations/de.php
application/modules/awards/translations/en.php
application/modules/awards/views/admin/index/index.php
application/modules/awards/views/admin/index/treat.php
application/modules/awards/views/index/index.php
application/modules/awards/views/index/show.php

- Support multiple recipients
-- Added a new view (frontend, show action) for an award to see all recipients (in case there are a lot of recipients). Limited the amount of recipients to display on the overviews (frontend, index action and admincenter, index action) to 6.
-- Created a new table to hold all recipients of the awards.
- Fixed "clear" button on image selection
- Code style fixes
Fixes #441

Awards: Support multiple recipients

---

application/modules/admin/config/config.php

Remove jquery.bxslider on update. The only known usage is the partner module. With the last version of that module bxslider got integrated into the module.
The removal of jquery.bxslider was announced in the news of ilch 2.1.50.
https://github.com/IlchCMS/Ilch-2.0/releases/tag/v2.1.50

Remove jquery.bxslider on update

---

application/modules/gallery/mappers/Image.php
application/modules/gallery/views/index/show.php
application/modules/gallery/views/index/showimage.php

Deleting an image in the media module, which is used in a gallery of the gallery module caused an exception.
- Fix "setImageUrl(): Argument must be of type string, null given"
- Further improved the views for handling a missing image.
```
Fatal error: Uncaught TypeError: Modules\Gallery\Models\Image::setImageUrl(): Argument #1 ($imageUrl) must be of type string, null given, called in application\modules\gallery\mappers\Image.php on line 144 and defined in application\modules\gallery\models\Image.php:225
Stack trace:
#0 application\modules\gallery\mappers\Image.php(144): Modules\Gallery\Models\Image->setImageUrl(NULL)
#1 application\modules\gallery\controllers\admin\Gallery.php(81): Modules\Gallery\Mappers\Image->getImageByGalleryId(2, Object(Ilch\Pagination))
#2 …
```

Gallery: Fix "Argument must be of type string, null given"

---

application/modules/gallery/controllers/admin/Index.php

- Fix errors when trying to delete a category.
-- Fix "key_exists(): Argument ($array) must be of type array, null given"
-- Fix "foreach() argument must be of type array|object, null given"
```
Warning: foreach() argument must be of type array|object, null given in application\modules\gallery\controllers\admin\Index.php on line 53
Fatal error: Uncaught TypeError: key_exists(): Argument #2 ($array) must be of type array, null given in application\modules\gallery\controllers\admin\Index.php:70
Stack trace:
#0 application\modules\gallery\controllers\admin\Index.php(70): key_exists(1, NULL)
#1 application\libraries\Ilch\Page.php(241): Modules\Gallery\Controllers\Admin\Index->indexAction()
#2 application\libraries\Ilch\Page.php(135): Ilch\Page->loadController()
#3 index.php(66): …
```

Fix errors when trying to delete a category.

---

application/modules/gallery/boxes/Pictureofx.php
application/modules/gallery/config/config.php

Gallery: Remove usage of no longer existing column 'cat'

Gallery: Remove usage of no longer existing column 'cat'

---

application/libraries/Ilch/Config/Database.php
application/libraries/Ilch/Config/File.php
application/modules/admin/config/config.php

Reduce db queries caused by the config.
Set a default value if it hasn't a value for 'mod_rewrite' and 'multilingual_acp' as it is causing a lot of database queries if not set and therefore not gets cached.
Example: Reduction of db queries from 218 to 124 ('multilingual_acp' set) and further down to 115 ('mod_rewrite' set) for the forum module index action in this dev environment.

Reduce db queries caused by the config

---

application/modules/user/config/config.php

Remove jquery.nicescroll.js. Got replaced by a newer and minified version.

Remove jquery.nicescroll.js

---

application/modules/admin/config/config.php
application/modules/bbcodeconvert/config/config.php
application/modules/bbcodeconvert/controllers/admin/Index.php
application/modules/bbcodeconvert/mappers/Texts.php
application/modules/bbcodeconvert/mappers/User.php
application/modules/bbcodeconvert/static/css/bbcodeconvert_styles.css
application/modules/bbcodeconvert/translations/de.php
application/modules/bbcodeconvert/translations/en.php
application/modules/bbcodeconvert/views/admin/index/convert.php
application/modules/bbcodeconvert/views/admin/index/index.php
application/modules/bbcodeconvert/views/admin/index/note.php

Add bbcodeconvert module. This module is used to convert items (guestbook messages, posts in the forum, ...) from BBCode to HTML. This is needed as in preparation for a move to CKEditor 5, which doesn't support BBCode, we migrate the modules and layouts to use the CKEditor 4 in HTML mode. This module should be supported for some time after the move to HTML mode and CKEditor 5 to allow everyone to convert the items. After that it can be removed from the repo.
- https://github.com/IlchCMS/Ilch-2.0/pull/701
ToDo:
- Add this module to the next ilch update. It should not be part of a new install of ilch.
- ~~Adjust version numbers of supported ilch versions and module/layout versions.~~

Add bbcodeconvert module

---

application/modules/bbcodeconvert/controllers/admin/Index.php

bbcodeconvert: fix wrong version number

bbcodeconvert: fix wrong version number

---

application/modules/bbcodeconvert/controllers/admin/Index.php

Fix wrong type for "contact_welcomeMessage". The value column of the config table is of type TEXT.

bbcodeconvert: Fix wrong type for "contact_welcomeMessage"

---

application/modules/gallery/controllers/admin/Settings.php

- Fix "implode(): Argument must be of type array, string given"
- Fix "explode(): Passing null to parameter of type string is deprecated"

Gallery: Fix errors in Settings.php

---

application/modules/shop/config/config.php
application/modules/shop/mappers/Items.php

Fehler: An unexpected error occurred:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND `status` = "1") GROUP BY `cat_id`' at line 1
Dieser trat auf, wenn der Shop ohne Kategorie und Produkte im Frontend aufgerufen wurde.

Shop module: Fix error on empty shop

---

application/modules/article/boxes/views/keywords.php

- fix wrong url in keywords box
When opening a page of another module. The URLs for the article keywords box used that module key instead of "article".

article: fix wrong url in keywords box

---

application/modules/shop/config/config.php
application/modules/shop/views/index/cart.php

- Fix errors when the shopping cart is empty
- Update version number to 1.1.2
> Undefined variable: total_price in application/modules/shop/views/index/cart.php
Undefined variable: shipping_costs in application/modules/shop/views/index/cart.php
Undefined variable: arrayShippingCosts in application/modules/shop/views/index/cart.php
max(): When only one parameter is given, it must be an array in application/modules/shop/views/index/cart.php
Undefined variable: total_price in application/modules/shop/views/index/cart.php

Shop: Fix errors when the shopping cart is empty

---

application/modules/user/controllers/admin/Providers.php
application/modules/user/mappers/AuthProvider.php
application/modules/user/models/AuthProviderModule.php
application/modules/user/models/Provider.php
application/modules/user/views/admin/providers/index.php

- Fix "Creation of dynamic property module_name is deprecated" and more

Auth providers: Fix "Creation of dynamic property module_name is deprecated" and more

---

application/libraries/Ilch/Pagination.php
application/modules/forum/boxes/views/forum.php
application/modules/forum/config/config.php
application/modules/forum/controllers/Showposts.php
application/modules/forum/views/Showunansweredtopics/index.php
application/modules/forum/views/showcat/index.php
application/modules/forum/views/shownewposts/index.php
application/modules/forum/views/showtopics/index.php

- Mark topic as read if on the last page or on the first page with descending post order.
- Added a getter for rows in the pagination class to use it in the forum. Therefore the forum now requires Ilch 2.1.53.

Forum:  Add mark topic as read conditions

---

application/modules/user/models/Dialog.php

- Fix errors in the dialog
> Uncaught TypeError: Modules\User\Models\Dialog::getId(): Return value must be of type int, null returned
> ...

User: Fix errors in the dialog

---

application/modules/admin/config/config.php
composer.lock

- Update PHPMailer to 6.8.1
> The DSN support added in 6.8.0 reflects the DSN back to the user in an error message if it is invalid. If a DSN uses user-supplied input (a very bad idea), it opens a distant possibility of XSS if the host app does not escape output. In an abundance of caution, malformed DSNs are no longer reflected in error messages.

Update PHPMailer to 6.8.1

---

application/modules/faq/config/config.php
application/modules/faq/views/admin/cats/index.php

Dieser Fehler trat auf, wenn man eine neue Kategorie anlegen wollte.
```
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in ilch_normal\application\modules\faq\views\admin\cats\index.php:36
Stack trace:
#0 ilch_normal\application\libraries\Ilch\View.php(22): include()
#1 ilch_normal\application\libraries\Ilch\Page.php(151): Ilch\View->loadScript('')
#2 ilch_normal\index.php(67): Ilch\Page->loadPage()
#3 {main} thrown in ilch_normal\application\modules\faq\views\admin\cats\index.php on line 36
```

FAQ: Fix "Argument must be of type Countable|array, null given"

---

application/modules/downloads/config/config.php
application/modules/downloads/mappers/File.php
application/modules/downloads/views/index/show.php

- Fix comments by setting the id for the file in the getFileById function.
- Fix visits count being displayed in bold.
Fixes #783

Downloads: Fix comments

---

application/libraries/Ilch/Functions.php
application/modules/admin/controllers/admin/Backup.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/backup/index.php
application/modules/downloads/config/config.php
tests/libraries/ilch/FunctionsTest.php

- Backup: Add filesize to the backups table
- Backup: Don't show random part of the backup filename.
- Added formatBytes function for global usage in Ilch and unit tests for it.
- Reverted change of the version number of the downloads module.
I was expecting to find a function like formatBytes in the Functions class, but looks like we always used separate solutions. So added one now, that should also support bigger numbers.
https://github.com/IlchCMS/Ilch-2.0/blob/b448585d8f5f1716699f9767e5284a5fbc097f39/application/modules/user/mappers/Setting.php#L19
https://github.com/IlchCMS/Ilch-2.0/blob/b448585d8f5f1716699f9767e5284a5fbc097f39/application/modules/media/static/js/script.js#L104
https://github.com/IlchCMS/Ilch-2.0/blob/b448585d8f5f1716699f9767e5284a5fbc097f39/build/optimize_vendor.php# …

Add filesize of backup and cleanup filename, add formatBytes function

---

application/libraries/Ilch/Upload.php

- Don't try to create a thumbnail if getimagesize returns false. Either damaged image or no image at all.
- Code improvements
Fixes #806

media, downloads and other modules: Fix errors handling non-image files

---

application/modules/forum/config/config.php

- Improved the performance of a query.
Added additional FKCs and therefore indices to the posts and topics table to fix a slow query. For example reduced from ~530 ms to ~54 ms with the tables on the dev system.
The query in this function was slow:
https://github.com/IlchCMS/Ilch-2.0/blob/master/application/modules/forum/mappers/Forum.php#L39

Forum: improve performance of query

---

application/modules/user/controllers/Panel.php
application/modules/user/mappers/Dialog.php
application/modules/user/models/Dialog.php

- Fix errors in dialog when other user got deleted
- Remove call of getDialogMessage in the dialog action as it seems to be not used in the view.
Fixes #813

User: Fix errors in dialog when other user got deleted

---

application/modules/forum/config/config.php

- Fix alter table statement
`ALTER TABLE tbl_name CHANGE [COLUMN] old_col_name new_col_name column_definition [FIRST | AFTER col_name]`
https://dev.mysql.com/doc/refman/5.7/en/alter-table.html
https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

Forum: fix alter table statement

---

application/modules/user/mappers/Dialog.php

- Fix "file_exists(): Passing null to parameter"

Fix "file_exists(): Passing null to parameter"

---

.github/pull_request_template.md
application/modules/user/mappers/Dialog.php

Empty instead isset

---

application/modules/forum/config/config.php
application/modules/forum/controllers/Showactivetopics.php
application/modules/forum/controllers/Shownewposts.php
application/modules/forum/controllers/Showunansweredtopics.php
application/modules/forum/mappers/Forum.php
application/modules/forum/mappers/Topic.php

- Fixed errors with empty forums, categories or none existing
- Fixed some "Invalid argument supplied for foreach()" errors.
Fixes #846

Forum: Fix errors with empty forums, categories or none existing

---

application/modules/install/controllers/Index.php

Install: remove space in front of "MariaDB"

Install: remove space in front of "MariaDB"

---

application/modules/install/translations/de.php
application/modules/install/translations/en.php

Install: fix translation license file
A file called license.html no longer exists.

Install: fix translation license file

---

application/modules/calendar/config/config.php
application/modules/calendar/views/events/index.php

- escape() breaks title
Fixes #858

Calendar: escape() breaks title

---

application/modules/forum/boxes/Forum.php
application/modules/forum/config/config.php
application/modules/forum/mappers/Forum.php
application/modules/forum/mappers/Topic.php

- Fixed errors in the box with nothing to show.
- Fixed sorting of topics with the newest posts in getLastPostsByTopicIds.
- Fixed sorting in getLastPostsByForumIds.
- Fixed read status in getLastPostsByTopicIds.
getLastPostsByTopicIds needs an additional check if datetime is newer than the newest post of the topic as topic_read was always set.

Forum: Fix errors in the box and more

---

application/modules/awards/config/config.php
application/modules/awards/views/admin/index/treat.php

- Fix "in_array(): Argument 2 must be of type array, string given"

Awards: Fix "in_array(): Argument 2 must be of type array, string given"

---

application/modules/forum/controllers/Newpost.php

- Fix duplicated entries in topic_read table
Previously the topic was marked as read when creating a post and after a redirect when showing it. This might fail in this way, because the first row doesn't exist yet?
Fixes #862

Forum: Fix duplicated entries in topic_read table

---

application/libraries/Ilch/Design/Base.php

Adjust the HTMLPurifier configuration to allow base64 encoded images.

HTMLPurifier: Allow base64 encoded images

---

application/modules/link/controllers/admin/Index.php
application/modules/link/translations/de.php
application/modules/link/translations/en.php

- Fixed "argument must be of type array|object, null given"
- Improved the menus.

Fix "argument must be of type array|object, null given"

---

application/modules/forum/mappers/Forum.php

Forum: fix missing select variable

---

application/modules/faq/config/config.php

- Fix order of table deletion on uninstall

faq: fix order of table deletion on uninstall

---

application/modules/vote/config/config.php
application/modules/vote/mappers/Vote.php
tests/modules/vote/_files/mysql_database.yml
tests/modules/vote/mappers/IpTest.php
tests/modules/vote/mappers/ResultTest.php
tests/modules/vote/mappers/VoteTest.php

Vote V1.12.1 - update

---

.github/workflows/build.yaml
.github/workflows/ci.yaml

- Update GitHub actions
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Update GitHub actions

---

application/modules/newsletter/boxes/Newsletter.php
application/modules/newsletter/boxes/views/newsletter.php
application/modules/newsletter/config/config.php
application/modules/newsletter/controllers/Index.php
application/modules/newsletter/controllers/admin/Index.php
application/modules/newsletter/controllers/admin/Receiver.php
application/modules/newsletter/controllers/admin/Settings.php
application/modules/newsletter/layouts/mail/doubleOptIn.php
application/modules/newsletter/mappers/Newsletter.php
application/modules/newsletter/mappers/Subscriber.php
application/modules/newsletter/models/Newsletter.php
application/modules/newsletter/models/Subscriber.php
application/modules/newsletter/translations/de.php
application/modules/newsletter/translations/en.php
application/modules/newsletter/views/admin/index/index.php
application/modules/newsletter/views/admin/index/show.php
application/modules/newsletter/views/admin/settings/index.php
application/modules/newsletter/views/index/index.php
application/modules/newsletter/views/index/settings.php
application/modules/newsletter/views/index/show.php

- Added support for double opt in (enabled by default).
- Splitted up "newsletter" model and "newsletter" mapper by adding a "subscriber" model and mapper.
- Changed setter and getter of Newsletter (now in subscriber mapper) to Boolean.
- #635
- Code style changes
Fixes #514

Newsletter: Add support for double opt in

---

application/modules/admin/layouts/index.php
application/modules/admin/layouts/maintenance.php
application/modules/admin/static/css/admin.css
application/modules/admin/static/css/extsearch.css
application/modules/admin/views/admin/infos/logs.php
application/modules/admin/views/admin/layouts/show.php
application/modules/admin/views/admin/modules/show.php
application/modules/article/views/admin/cats/index.php
application/modules/article/views/admin/index/treat.php
application/modules/article/views/index/show.php
application/modules/bbcodeconvert/views/admin/index/convert.php
application/modules/birthday/views/index/index.php
application/modules/media/views/admin/index/index.php
application/modules/shop/views/index/cart.php
application/modules/shop/views/index/order.php
application/modules/shop/views/index/success.php
application/modules/shoutbox/boxes/views/shoutbox.php
application/modules/teams/views/admin/index/index.php
application/modules/user/views/admin/profilefields/treat.php
application/modules/user/views/login/index.php
application/modules/user/views/panel/providers.php

- Renamed .close to .btn-close
- Renamed .sr-only to .visually-hidden
- Replaced center-block with mx-auto
- Replaced navbar-toggle with navbar-toggler
- bg-success and progress-bar-animated
- Renamed .divider to .dropdown-divider.
- Replaced btn-default with btn-secondary.
- Replaced btn-xs with btn-sm.
See
https://www.ilch.de/forum-showposts-58597-p5.html#408094

BS5: Various smaller changes

---

static/js/ckeditor/config_ilch_html.js
static/js/ckeditor/config_ilch_html_frontend.js

Disables the version check of CKEditor 4.22.1 to prevent the "not secure" warning from popping up on every load of the CKEditor.
This is obviously not a long term solution. The switch to CKEditor 5 (together with Bootstrap 5) is currently in progress and planned to be done asap, but still requires some time. With the current configuration of CKEditor 4 and what we distribute of the CKEditor 4.22.1 as part of Ilch we are likely not directly affected by the security issues fixed with CKEditor 4.24.0 LTS.

CKEditor 4: Set versionCheck to false

---

application/libraries/Ilch/Design/Base.php
application/libraries/Ilch/HTMLPurifier/EmbedUrlDef.php
static/js/ilch.js

- Change configuration of media embed and HTML Purifier.
So sieht es aktuell im CKEditor 4.22.1 (Frontend) aus:
Im Backend haben wir ja das "ilchmedia"-Plugin was noch paar mehr Funktionen hat.

CKEditor 5: Media embed and HTML Purifier

---

application/modules/admin/views/admin/settings/index.php
application/modules/admin/views/admin/settings/mail.php
application/modules/away/views/admin/settings/index.php
application/modules/partner/views/admin/settings/index.php
application/modules/user/views/admin/profilefields/treat.php
application/modules/user/views/admin/settings/index.php

- Replaced the removed hidden class with the hidden attribute.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
`The .hidden and .show classes have been removed because they conflicted with jQuery’s $(...).hide() and $(...).show() methods. Instead, try toggling the [hidden] attribute or use inline styles like style="display: none;" and style="display: block;".`
https://getbootstrap.com/docs/4.1/migration/#responsive-utilities

BS5: Replace removed hidden class

---

application/modules/newsletter/config/config.php
application/modules/newsletter/controllers/Index.php

````
Fatal error: Uncaught TypeError: Modules\Newsletter\Models\Subscriber::getDoubleOptInDate(): Return value must be of type string, null returned in application\modules\newsletter\models\Subscriber.php:159
Stack trace:
#0 application\modules\newsletter\mappers\Subscriber.php(151): Modules\Newsletter\Models\Subscriber->getDoubleOptInDate()
#1 application\modules\newsletter\controllers\Index.php(154): Modules\Newsletter\Mappers\Subscriber->saveUserAsSubscriber(Object(Modules\Newsletter\Models\Subscriber))
#2 application\libraries\Ilch\Page.php(241): Modules\Newsletter\Controllers\Index->settingsAction()
#3 application\libraries\Ilch\Page.php(135): Ilch\Page->loadController()
#4 index.php(68): Ilch\Page->loadPage()
#5 {main} thrown in application\modules\newsletter\models\Subscriber.php …
```

Newsletter: Fix "Return value must be of type string, null returned"

---

application/modules/forum/config/config.php
application/modules/forum/mappers/Forum.php
application/modules/forum/mappers/Topic.php

- Get last id of post instead of first.
- Fix group with wrong column in getCountPostsByTopicIds. This caused the function to always return counts of 1.
Previously the first post of the topic was linked in various places instead of the newest one.

Forum: last id of post instead of first, wrong counts with getCountPostsByTopicIds

---

application/modules/admin/config/config.php
index.php

**Version 2.1.59**
Als eine der letzten offiziell unterstützten Versionen von Linux-Distributionen mit PHP 7.3 wird Debian 10 am 30. Juni 2024 den Support einstellen. Ab diesem Stichtag wird auch Ilch 2 kein PHP 7.3 mehr unterstützen. Wir empfehlen daher rechtzeitig auf neuere PHP-Versionen zu wechseln.  
Sollten Sie noch Inhalte im BBCode-Format haben, wird empfohlen diese bis vor Mitte des Jahres zu konvertieren. Ab diesem Zeitpunkt wird das BBCode-Konvertierung-Modul nicht mehr gepflegt.  
<a href="https://github.com/IlchCMS/Ilch-2.0/wiki/Hinweise-f%C3%BCr-Entwickler" target="_blank">Hinweise für Entwickler</a>  
**Ilch:**  
- Die erweiterten Layout-Einstellungen wurden um den Typen "textarea" erweitert.  
- Der Typ "text" der erweiterten Layout-Einstellungen erlaubt nun 255 Zeichen, …

V2.1.59-Beta

---

application/modules/admin/views/admin/backup/index.php

Show "noBackups" message instead of garbled table

Backup: Show "noBackups" message instead of garbled table

---

application/modules/article/controllers/Index.php

Article: Fix "Passing null to parameter of type string is deprecated" in preview

Article: Fix "Passing null to parameter of type string is deprecated"

---

application/modules/admin/controllers/admin/Layouts.php
application/modules/training/config/config.php
application/modules/training/mappers/Entrants.php
application/modules/training/views/index/index.php
index.php

**Version 2.1.60**
Als eine der letzten offiziell unterstützten Versionen von Linux-Distributionen mit PHP 7.3 wird Debian 10 am 30. Juni 2024 den Support einstellen. Ab diesem Stichtag wird auch Ilch 2 kein PHP 7.3 mehr unterstützen. Wir empfehlen daher rechtzeitig auf neuere PHP-Versionen zu wechseln.  
Sollten Sie noch Inhalte im BBCode-Format haben, wird empfohlen diese bis vor Mitte des Jahres zu konvertieren. Ab diesem Zeitpunkt wird das BBCode-Konvertierung-Modul nicht mehr gepflegt.  
<a href="https://github.com/IlchCMS/Ilch-2.0/wiki/Hinweise-f%C3%BCr-Entwickler" target="_blank">Hinweise für Entwickler</a>  
**Ilch:**  
- Einige erweiterte Layout Einstellungen wurden seit Ilch 2.1.59 nicht gespeichert.  
**Artikel-Modul:**  
- Fehler in der Vorschau behoben.  
**Benutzer-Modul:** …

Version 2.1.60

---

application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/layouts/index.php
application/modules/admin/views/admin/layouts/search.php
application/modules/admin/views/admin/modules/index.php
application/modules/admin/views/admin/modules/notinstalled.php
application/modules/admin/views/admin/modules/search.php
application/modules/admin/views/admin/modules/updates.php

Add checks to make sure the layout or module is compatible with Ilch 2.2.0 or newer or in other words has been adjusted for Bootstrap 5.

Layouts and modules: Check if compatible with Ilch >= 2.2.0

---

application/modules/admin/views/admin/layouts/advSettingsShow.php

- Update advSettingsShow.php to remove "ckeditorbbcode" as this can no longer be supported with CKEditor 5.

Update advSettingsShow.php to remove "ckeditorbbcode"

---

.github/workflows/build.yaml

Use recommended "ubuntu-latest" and a newer php version in setup-php.
According to the setup-php documentation PHP 8.0 is end of life.
https://github.com/shivammathur/setup-php?tab=readme-ov-file#tada-php-support
August 2022
> Ubuntu 22.04 is now generally available on GitHub-hosted runners. To use it now, simply add runs-on: ubuntu-22.04 in your workflow file. **Otherwise, our recommendation is to use ubuntu-latest**, which currently utilizes Ubuntu 20.04 but will begin running on Ubuntu 22.04 in the near future.
https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

Use recommended "ubuntu-latest" and newer php

---

application/modules/admin/mappers/Menu.php

- Improve getMenus function. It unnecessarily called getMenu() inside a for loop multiple times when the menus could have been got from the database with one query.
- Some smaller code style improvements.

Improve getMenus function

---

application/modules/linkus/config/config.php
application/modules/linkus/views/index/index.php

- Use "bg-body-tertiary" for textareas

Linkus: Use "bg-body-tertiary" for textareas

---

index.php
static/js/ckeditor5/package-lock.json
static/js/ckeditor5/package.json

- Rebuild CKEditor 5
- Bumps ws from 7.5.9 to 7.5.10.

Rebuild CKEditor 5: Fixed security issue in ws

---

development/bin/setup.sh
development/vagrant/Vagrantfile

Die VM "debian/contrib-bullseye64" gibt es nicht und das build-Script wurde geändert

Vagrant: Box "debian/contrib-bullseye64" existiert nicht mehr, Build-Skript wurde umbenannt

---

application/libraries/Ilch/Design/Base.php
tests/libraries/ilch/Design/BasePurifyTest.php

HTML Purifier: Allow mailto

---

application/modules/admin/config/config.php
index.php

**Version 2.2.2**  
Dies ist die erste Version, die kein PHP 7.3 mehr unterstützt. Als eine der letzten offiziell unterstützten Versionen von Linux-Distributionen mit PHP 7.3 hat Debian 10 am 30. Juni 2024 den Support eingestellt. Diesen Zeitpunkt haben wir genommen um auch die Unterstützung von Ilch für PHP 7.3 einzustellen.  
Außerdem wird das BBCode-Konvertierung-Modul nicht mehr gepflegt. Sollten Sie noch Inhalte im BBCode-Format haben, wird empfohlen diese vor dem Update auf Ilch 2.2.2 zu konvertieren.  
Mit dieser Version wird ebenfalls ein neues Zertifikat verteilt. Installieren Sie das Update idealerweise zeitnah, um weiterhin wie bisher Module und Layouts installieren oder aktualisieren zu können, spätestens jedoch bis zum 31.01.2025, da Ilch ab diesen Zeitpunkt ansonsten keine …

Betatest 2.2.2

---

application/modules/admin/config/config.php
application/modules/admin/views/admin/index/index.php
application/modules/admin/views/admin/settings/notifications.php

- Admincenter notifications clarification
- Permission for admin module granted in case the user unintentionally revoked it
Now icons are used that are more commonly associated with (enabled, disabled, muted, ...) notifications.
Button for disabling/muting notifications of this module on the admincenter startpage is now using the bell-slash icon.
Buttons for changing the permission now dispaly the current state with the bell icons.

Admincenter notifications clarification

---

application/modules/admin/mappers/Menu.php

Missed one with the previous PR https://github.com/IlchCMS/Ilch-2.0/pull/1013
- Fix "Implicitly marking a parameter as nullable"
#917

Fix "Implicitly marking a parameter as nullable"

---

application/libraries/Ilch/DebugBar/DataCollector/MysqlCollector.php

Update MysqlCollector used in the DebugBar. This is a custom class and not part of DebugBar.
Fixes #917

Update MysqlCollector used in the DebugBar (PHP 8.4 support)

---

application/libraries/Ilch/Transfer.php

- Code style improvements.
- Remove curlOpt array as the stored cURL options where never used after saving them in that array. The way the options where stored wasn't useful either as a cURL option is "tied" to a specific transfer (transferUrl). This shouldn't affect the functionality as the important function call for cURL is curl_setopt().
- Remove getVersionsList() as it was only used in newVersionFound() of the transfer class itself and just one time. A second call was unnecessary.
- Don't set zipFile in newVersionFound(). This caused an error (under PHP 8.2) and looks like it wasn't needed.
- Verify file right before installing.
- https://github.com/IlchCMS/Ilch-2.0/pull/962
Tested the changes by using this new Transfer.php in an install of Ilch 2.1.60 to update it to Ilch 2.2.2 and …

Transfer class: code improvements

---

application/libraries/Ilch/Transfer.php

- Fix storing curl options in array

Fix storing curl options in array

---

application/modules/admin/controllers/admin/Index.php
application/modules/admin/static/css/admin.css
application/modules/admin/views/admin/index/index.php

- Cache news for the current default of 6 hours, but add refresh button.
Previously this was only cached for 2 minutes, which probably lead to a lot of unnecessary loads. Added a refresh button to allow the user to get the latest news immediately.

Cache news for 6 hours, but add refresh button

---

application/libraries/Ilch/Database/Factory.php

- Fix "database is already a registered collector"
This error was triggered by the ilch1importer module.

Fix "database is already a registered collector"

---

application/modules/events/config/config.php
application/modules/events/views/show/event.php

- Fixed "explode(): Passing null to parameter of type string is deprecated"

Events: Fix "explode(): Passing null to parameter of type string is deprecated"

---

.github/workflows/ci.yaml

Update ci.yaml to add PHP 8.4. Possible release date for PHP 8.4 is Nov 21 2024.

Update ci.yaml to add PHP 8.4

---

application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/settings/htmlpurifier.php

- Removed form, tokenfield and savebar
- Changed translation

HTMLPurifier: Remove form, tokenfield and savebar

---

application/modules/admin/controllers/admin/Backup.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/backup/index.php

- Add importing of a database dump.
Fixes #416
Remarks:
- The import button is red and disabled if the database backup is gzip compressed as importing these is currently not supported.
- Trying to import a backup with already existing tables throws an exception that is handled.
- > mysqldump-php error: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'ilch_admin_layoutadvsettings' already exists
- Obviously Ilch loses track of all kind of files (downloads, media, backups, ...) if a backup gets imported that was created before these files got added.

Add importing of a database dump

---

application/libraries/Ilch/Design/Base.php

- Fix syntax error in safeIframeRegexp
```
preg_match(): Compilation failed: unmatched closing parenthesis at offset 371 in application/libraries/Ilch/HTMLPurifier/EmbedUrlDef.php:18
preg_match(): Compilation failed: unmatched closing parenthesis at offset 371 in vendor/ezyang/htmlpurifier/library/HTMLPurifier/URIFilter/SafeIframe.php:64
```

HTMLPurifier: Fix syntax error in safeIframeRegexp

---

application/libraries/Ilch/Design/Base.php
application/libraries/Ilch/Page.php

- Fix "Return value of Ilch\Design\Base::getPurifier() must be an instance of HTMLPurifier, null returned"
```
Uncaught TypeError: Return value of Ilch\Design\Base::getPurifier() must be an instance of HTMLPurifier, null returned in application/libraries/Ilch/Design/Base.php:191
Stack trace:
#0 application/libraries/Ilch/Design/Base.php(210): Ilch\Design\Base->getPurifier()
#1 application/modules/user/controllers/Regist.php(188): Ilch\Design\Base->purify()
#2 application/libraries/Ilch/Page.php(242): Modules\User\Controllers\Regist->inputAction()
#3 application/libraries/Ilch/Page.php(136): Ilch\Page->loadController()
#4 index.php(68): Ilch\Page->loadPage()
#5 {main} thrown in application/libraries/Ilch/Design/Base.php on line 191
```

Fix "instance of HTMLPurifier, null returned"

---

application/modules/user/config/config.php
application/modules/user/controllers/Regist.php
application/modules/user/controllers/admin/Profilefields.php
application/modules/user/mappers/ProfileFields.php
application/modules/user/mappers/ProfileFieldsContent.php
application/modules/user/mappers/ProfileFieldsTranslation.php
application/modules/user/models/ProfileField.php
application/modules/user/models/ProfileFieldContent.php
application/modules/user/models/ProfileFieldTranslation.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php
application/modules/user/views/admin/index/treatProfile.php
application/modules/user/views/admin/profilefields/index.php
application/modules/user/views/admin/profilefields/treat.php
application/modules/user/views/index/index.php
application/modules/user/views/panel/profile.php
application/modules/user/views/profil/index.php
application/modules/user/views/regist/input.php

- Add feature to optionally query for additional profile fields on registration. They can be set to required as well.
- Profilefields-Mapper, getProfileFields(): Changed where clause to use the default "and" instead of "or". Possible breaking change.
- Added missing tooltip for the profile field list.
- Fix broken date fields in user panel profile. They broke when switching to TempusDominus with Ilch 2.2.0.
- Code style improvements
Fixes #619

Userdefined profile fields on registration

---

application/modules/user/config/config.php
application/modules/user/controllers/admin/Profilefields.php
application/modules/user/mappers/ProfileFields.php

Make use of foreign key constraints. When deleting a profile field we call functions for the profile field itself, the contents and the translations.
#1066

User profile fields: add FKCs

---

application/modules/user/config/config.php
application/modules/user/controllers/Panel.php
application/modules/user/controllers/admin/Index.php
application/modules/user/mappers/Group.php
application/modules/user/mappers/User.php
tests/modules/user/_files/mysql_database.yml

- Create updated tables on install, update tables on update and delete orphaned rows.
- Updated unit tests to add users before trying to add auth_tokens to fix failing unit tests.
- Removed code no longer needed after adding FKCs.
- auth_tokens (userid)
- groups_access (group_id)
- user_friends (user_id, friend_user_id)
- users_auth_providers (user_id)
- users_dialog (user_one, user_two)
- users_dialog_hidden (user_id)
- users_dialog_reply (user_id_fk)
- users_gallery_imgs (user_id)
- users_gallery_items (user_id)
- users_groups (user_id, group_id)
- users_media (user_id)
A FKC for visits_online (user_id) was not possible due to the default value of 0 for guests.
Fixes #1066

User module: Add several FKCs

---

application/modules/forum/config/config.php

- Allow longer forum posts by changing the datatype of the text column of the forum_posts table from TEXT to MEDIUMTEXT.
> Wenn ich einen sehr langen Bericht mit Bildern im Forum posten möchte, wird dieser bei der Hälfte abgeschnitten. Sind diverse Zeichenbegrenzer in den Feldern?
https://www.ilch.de/forum-showposts-58734.html#408628

Forum: Allow longer forum posts

---

composer.lock

- Update HTMLPurifier to v4.18.0. Adds support for PHP 8.4 and more.

Update HTMLPurifier to v4.18.0

---

application/modules/events/config/config.php
application/modules/events/views/show/event.php

- Use CKEditor and alwaysPurify() for comments.
- Fix empty comments box being shown.

Events module: Use CKEditor and alwaysPurify()

---

application/modules/user/views/index/index.php
application/modules/user/views/profil/index.php

- Fix possible duplicate in output
Example: 
```
addition = "https://discord.gg/"
value = "https://discord.gg/username"
The user entered the complete URL instead of just the username. The output was "https://discord.gg/https://discord.gg/username"
```
Fixes #509

User module: Fix possible duplicate (issue 509)

---

application/libraries/Ilch/Layout/Frontend.php
application/modules/cookieconsent/controllers/admin/Index.php
application/modules/cookieconsent/translations/de.php
application/modules/cookieconsent/translations/en.php
application/modules/cookieconsent/views/admin/index/index.php

- Add tarteaucitron services to the dialog when they are selected in the admincenter. This doesn't automatically adjust how the services are integrated into the website for it to take effect.
> If you have selected one or more services, you still need to adjust the integration of the services. Read more about this on the following page: [tarteaucitron.io/en/install/](https://tarteaucitron.io/en/install/)

CookieConsent: Add tarteaucitron services

---

application/libraries/Ilch/Design/Base.php

- Add Google Maps to SafeIframe

HTMLPurifier: Add Google Maps to SafeIframe

---

application/libraries/Ilch/Design/Base.php
application/libraries/Ilch/Page.php
tests/libraries/ilch/Design/BasePurifyTest.php

- Fix domain setting not being used in HTMLPurifier.
- Add "www.google.com/maps/" to safeIframeRegexp.
- Add two unit tests for Google Maps.
https://www.ilch.de/forum-showposts-58761.html

Fix domain setting not being used in htmlpurifier

---

application/modules/link/config/config.php
application/modules/link/controllers/Index.php

- Fix "Argument must be of type int, string given"
Fixes #1095

Link module: Fix "Argument must be of type int, string given"

---

application/modules/user/controllers/Profil.php

- Fix "Argument must be of type int, string given"
Fixes #1096

User module: Fix "Argument must be of type int, string given"

---

application/libraries/Ilch/Functions.php
application/modules/admin/controllers/admin/Menu.php
application/modules/admin/controllers/admin/Settings.php
application/modules/admin/mappers/Menu.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/settings/index.php
application/modules/cookieconsent/controllers/admin/Index.php

- Fix "createFromFormat(): Argument must not contain any null bytes"
- CookieConsent module: Fix "must be of type array, string given"
- Validate the selected (or posted) timezone.
- Handle deleting of last menu: A new empty menu will be created. Further the table will get truncated, which resets auto_increment. This should allow to recover from a "broken" menu from inside the admincenter instead of having to fix it manually in the database table.
```
Uncaught ValueError: DateTime::createFromFormat(): Argument #2 ($datetime) must not contain any null bytes in application/libraries/Ilch/Functions.php:478
Stack trace:
#0 application/libraries/Ilch/Functions.php(478): DateTime::createFromFormat()
#1 application/libraries/Ilch/Validation/Validators/Date.php(30): validateDate()
#2 …
```

Fix various errors

---

application/libraries/Ilch/Translations/de.php
application/libraries/Ilch/Translations/en.php
application/modules/shop/config/config.php
application/modules/shop/controllers/Customerarea.php
application/modules/shop/controllers/Index.php
application/modules/shop/controllers/Payment.php
application/modules/shop/controllers/admin/Currency.php
application/modules/shop/controllers/admin/Items.php
application/modules/shop/controllers/admin/Orders.php
application/modules/shop/controllers/admin/Settings.php
application/modules/shop/mappers/Currency.php

- Prevent invalid currency in settings
- Improve getCurrencyById

Shop module: Prevent invalid currency in settings

---

application/modules/admin/mappers/Module.php
application/modules/comment/controllers/admin/Index.php
application/modules/comment/views/admin/index/show.php
application/modules/downloads/config/config.php
application/modules/gallery/config/config.php
application/modules/shop/translations/de.php
application/modules/shop/translations/en.php
application/modules/war/config/config.php

- Fix errors trying to show comments of deleted modules.
- Delete comments on uninstall of module (downloads, gallery, war).
- Fix translations of shop module.

Fix errors trying to show comments of deleted modules

---

application/modules/admin/mappers/Module.php
development/vagrant/xdebug.ini

- Initialize modulesDB
- Update xdebug.ini
https://xdebug.org/docs/upgrade_guide
```
PHP Warning:  Undefined variable $modulesDB in application/modules/admin/mappers/Module.php on line 73
PHP Fatal error:  Uncaught TypeError: array_diff(): Argument #2 must be of type array, null given in application/modules/admin/mappers/Module.php:73
Stack trace:
#0 application/modules/admin/mappers/Module.php(73): array_diff()
#1 application/modules/admin/mappers/Module.php(196): Modules\Admin\Mappers\Module->getModulesNotInstalled()
#2 application/modules/admin/controllers/admin/Index.php(59): Modules\Admin\Mappers\Module->getVersionsOfModules()
#3 application/libraries/Ilch/Page.php(243): Modules\Admin\Controllers\Admin\Index->indexAction()
#4 application/libraries/Ilch/Page.php(137): …
```

Initialize modulesDB and update xdebug.ini

---

application/modules/training/config/config.php
application/modules/training/controllers/admin/Index.php
application/modules/training/views/admin/index/treat.php

- Use validator for more inputs.
- Fix redirect on negative validation result.
- Fix has-error class being applied to all inputs.
- Require at least the address of the voice or gameserver if enabled.

Training module: Use validator for more inputs

---

application/modules/media/controllers/admin/Index.php

Abort upload action if filename is missing
```
PHP Fatal error:  Uncaught TypeError: Ilch\Upload::setFile(): Argument #1 ($file) must be of type string, null given, called in application/modules/media/controllers/admin/Index.php on line 160 and defined in application/libraries/Ilch/Upload.php:101
Stack trace:
#0 application/modules/media/controllers/admin/Index.php(160): Ilch\Upload->setFile()
#1 application/libraries/Ilch/Page.php(243): Modules\Media\Controllers\Admin\Index->uploadAction()
#2 application/libraries/Ilch/Page.php(137): Ilch\Page->loadController()
#3 index.php(68): Ilch\Page->loadPage()
#4 {main}
thrown in application/libraries/Ilch/Upload.php on line 101
```

Media module: Abort upload action if filename is missing

---

application/modules/article/controllers/admin/Index.php

- Fix "Call to a member function getReadAccess() on null"
```
PHP Fatal error:  Uncaught Error: Call to a member function getReadAccess() on null in application/modules/article/controllers/admin/Index.php:191
Stack trace:
#0 application/libraries/Ilch/Page.php(243): Modules\Article\Controllers\Admin\Index->treatAction()
#1 application/libraries/Ilch/Page.php(137): Ilch\Page->loadController()
#2 index.php(68): Ilch\Page->loadPage()
#3 {main}
thrown in application/modules/article/controllers/admin/Index.php on line 191
```

Article module: Fix "Call to a member function getReadAccess() on null"

---

application/modules/user/controllers/admin/Index.php

- locked should not be required when creating a new user. This caused not being able to create a new user.

User: locked not required when creating user

---

application/modules/admin/translations/de.php
application/modules/article/controllers/Index.php
application/modules/article/translations/de.php
application/modules/article/translations/en.php
application/modules/user/controllers/Profil.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php

- Decline empty comment in article and user module.
```
PHP Fatal error:  Uncaught TypeError: Ilch\Comments::saveComment(): Argument #2 ($text) must be of type string, null given, called in application/modules/article/controllers/Index.php on line 157 and defined in application/libraries/Ilch/Comments.php:426
Stack trace:
#0 application/modules/article/controllers/Index.php(157): Ilch\Comments->saveComment()
#1 application/libraries/Ilch/Page.php(243): Modules\Article\Controllers\Index->showAction()
#2 application/libraries/Ilch/Page.php(137): Ilch\Page->loadController()
#3 index.php(68): Ilch\Page->loadPage()
#4 {main}
thrown in application/libraries/Ilch/Comments.php on line 426, referer: index.php/article/index/show/id/1
PHP Fatal error:  Uncaught TypeError: …
```

Decline empty comment

---

application/modules/newsletter/config/config.php
application/modules/newsletter/controllers/Index.php

- Redirect guests to login page when they try to view the newsletter settings.
- Set needed values for the Double-Opt-In feature.
```
PHP Fatal error:  Uncaught Error: Call to a member function getEmail() on null in application/modules/newsletter/controllers/Index.php:165
Stack trace:
#0 application/libraries/Ilch/Page.php(243): Modules\Newsletter\Controllers\Index->settingsAction()
#1 application/libraries/Ilch/Page.php(137): Ilch\Page->loadController()
#2 index.php(68): Ilch\Page->loadPage()
#3 {main}
thrown in application/modules/newsletter/controllers/Index.php on line 165
```
```
PHP Fatal error:  Uncaught TypeError: Modules\Newsletter\Models\Subscriber::getDoubleOptInDate(): Return value must be of type string, null returned in …
```

Newsletter: Redirect guest to login page

---

application/libraries/Ilch/Functions.php
application/modules/shop/views/index/cart.php
index.php
tests/libraries/ilch/FunctionsTest.php
tests/libraries/ilch/Validation/Validators/DateTest.php

**Version 2.2.5**  
**Änderungen**  
<u>Ilch:</u>  
- "Angemeldet bleiben?" beim Admin-Login ermöglichen.  
- Cookieconsent entfernt. Nutzen nun in Ilch und im Cookie-Richtlinien-Modul "Tarteaucitron" anstatt "Cookieconsent".  
- Kommentare nutzen nun, wie z.B. das Forum den CKEditor.  
- Die neue Konfigurationsmöglichkeit für die Domain wurde in einigen Fällen nicht angewendet.  
- Zwei Domains für Google Maps zur Liste sicherer Domains hinzugefügt.  
- Es lassen sich nun in den Einstellungen weitere Domains zur Liste sicherer Domains hinzufügen.  
- Zeitzonen (timezone)-Validator hinzugefügt. Unterstützt alle aktuell gültigen Zeitzonen und auf Wunsch für die Abwärtskompatibilität auch inzwischen nicht mehr gültige.  
- Es konnte eine ungültige Zeitzone im Admincenter in den …

Beta 2.2.5

---

application/modules/teams/config/config.php
application/modules/teams/views/index/index.php

- Fix argument not int in teams view
```
Uncaught TypeError: Modules\User\Mappers\User::getUserById(): Argument #1 ($id) must be of type int, string given, called in application/modules/teams/views/index/index.php on line 50 and defined in application/modules/user/mappers/User.php:24
Stack trace:
#0 application/modules/teams/views/index/index.php(50): Modules\User\Mappers\User->getUserById()
#1 application/libraries/Ilch/View.php(22): include('...')
#2 application/libraries/Ilch/Page.php(161): Ilch\View->loadScript()
#3 index.php(68): Ilch\Page->loadPage()
#4 {main} thrown in application/modules/user/mappers/User.php on line 24
```

Teams: Fix argument not int in teams view

---

application/modules/user/controllers/admin/Index.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php

- Add user group required info message
When saving a user without a user group the user group "user" gets assigned by default. Added an info message as this might be unexpected.

User: Add user group required info message

---

application/modules/article/views/admin/index/treat.php

- Restore category selection after validation error. Otherwise show saved selected categories.

Article: Restore category selection after validation error

---

application/modules/admin/controllers/admin/Layouts.php
application/modules/admin/controllers/admin/Modules.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php

- Do not try to uninstall a system module.
- Fix error on uninstall action with invalid module key.
- Check if layoutKey could be valid.
- Add error messages and use correct message for uninstall.
- Remove dead variable.
```
Fatal error: Uncaught Error: Class '\Modules\Aaaa\Config\Config' not found in application/modules/admin/controllers/admin/Modules.php:425
Stack trace:
#0 application/libraries/Ilch/Page.php(243): Modules\Admin\Controllers\Admin\Modules->uninstallAction()
#1 application/libraries/Ilch/Page.php(137): Ilch\Page->loadController()
#2 index.php(68): Ilch\Page->loadPage()
#3 {main}
thrown in application/modules/admin/controllers/admin/Modules.php on line 425
```
```
PHP Fatal error:  Uncaught Error: Class "\Layouts\Layouts\Config\Config" not found in …
```

Do not try to uninstall a system module and check module and layout key

---

application/modules/admin/config/config.php
application/modules/admin/mappers/Module.php
application/modules/install/config/config.php
application/modules/install/controllers/Index.php

- Add FKCs to the modules tables (modules_boxes_content, modules_content, modules_folderrights, modules_php_extensions).
- Add all modules to modules table (this was required for the FKC for modules_boxes_content and is done in the install module).
- Add config.php for install module.
- Remove some info from config.php of error module as it would otherwise be added to the module menu.
**table:** modules_boxes_content, **column:** modules
**table:** modules_content, **column:** key
**table:** modules_folderrights, **column:** key
**table:** modules_php_extensions, **column:** key
> The column key of modules_boxes_content is not a module key (examples: lastwar, nexttraining, ...).
> ~~The column module of modules_boxes_content previously could contain module keys that where not in the …

Add FKCs to the modules tables

---

application/libraries/Ilch/Database/Mysql.php
tests/libraries/ilch/Database/MysqlTest.php

- Add ifForeignKeyConstraintExists and getDatabaseName

Add ifForeignKeyConstraintExists and getDatabaseName

---

application/modules/user/controllers/Login.php
application/modules/user/service/Login.php
application/modules/user/service/Remember.php

RememberMe: Remove unused parameter

---

application/modules/user/mappers/ProfileFields.php

- key is a string so this function should expect a string and not an int.
https://www.ilch.de/forum-showposts-58774.html

User module: Update ProfileFields getProfileFieldIdByKey()

---

application/modules/admin/controllers/admin/Index.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php

- Fix error when check for module updates failed
```
Invalid argument supplied for foreach() in application/modules/admin/controllers/admin/Index.php:60
```

Admincenter: Fix error when check for module updates failed

---

application/modules/training/boxes/views/nexttraining.php
application/modules/training/config/config.php
application/modules/training/controllers/Index.php
application/modules/training/controllers/Trainings.php
application/modules/training/controllers/admin/Index.php
application/modules/training/mappers/Training.php
application/modules/training/models/Training.php
application/modules/training/translations/de.php
application/modules/training/translations/en.php
application/modules/training/views/admin/index/index.php
application/modules/training/views/admin/index/treat.php
application/modules/training/views/index/index.php
application/modules/training/views/index/show.php
application/modules/training/views/trainings/index.php
tests/modules/training/_files/mysql_database.yml
tests/modules/training/mappers/TrainingTest.php

- Add support for recurrent events.
- Replaced the time column and it's getter and setter with the end column.
- Use validator for date inputs.
Fixes #428 
- ...

Training module: Add support for recurrent events

---

application/modules/away/config/config.php
application/modules/away/controllers/Index.php
application/modules/away/controllers/admin/Index.php
application/modules/user/mappers/User.php
tests/modules/user/mappers/UserTest.php

- Add getUserListByGroupIds() to user mapper and use that function in the away module.
- Require ilchCore 2.2.7 for the away module.
- Add unit tests for getUserListByGroupIds() and getUserListByGroupId().
Mit dem jetzt angegebenen Datentyp "int" für groupId tritt folgender Fehler auf:
```
Uncaught TypeError: Argument 1 passed to Modules\User\Mappers\User::getUserListByGroupId() must be of the type int, array given, called in application/modules/away/controllers/Index.php on line 93 and defined in application/modules/user/mappers/User.php:114
Stack trace:
#0 application/modules/away/controllers/Index.php(93): Modules\User\Mappers\User->getUserListByGroupId()
#1 application/libraries/Ilch/Page.php(243): Modules\Away\Controllers\Index->indexAction()
#2 …
```

Away: Fix broken user group notification feature

---

application/modules/user/views/index/index.php
application/modules/user/views/profil/index.php

- User: Fix error when handling profile link addition
```
Fatal error: Uncaught TypeError: substr_replace(): Argument #4 ($length) must be of type array|int|null, string given in application/modules/user/views/index/index.php:109
Stack trace:
#0 application/modules/user/views/index/index.php(109): substr_replace()
#1 application/libraries/Ilch/View.php(22): include('/homepages/18/d...')
#2 application/libraries/Ilch/Page.php(161): Ilch\View->loadScript()
#3 index.php(68): Ilch\Page->loadPage()
#4 {main} thrown in application/modules/user/views/index/index.php on line 109
```

User: Fix error when handling profile link addition

---

application/modules/events/config/config.php
application/modules/events/mappers/Events.php

- Fix "file_exists(): Passing null to parameter of type string is deprecated"
https://www.ilch.de/forum-showposts-58779.html

Fix "Passing null to parameter of type string is deprecated"

---

application/modules/forum/static/css/forum-items.css
application/modules/forum/views/admin/index/index.php

- Use choices instead of bootstrap tokenfield.
- Update CSS and move it to a file.
- Some other smaller changes.
Fixes #1157

Forum: Remove bootstrap tokenfield and update CSS

---

application/modules/training/mappers/Training.php

- Deprecate getTrainingsListWithLimt to remove it in one of the next versions.
- Some code style fixes.

Training: Deprecate getTrainingsListWithLimt

---

application/libraries/Thumb/Thumbnail.php

- Fix wrong if condition
> By default, version_compare() returns -1 if the first version is lower than the second, 0 if they are equal, and 1 if the second is lower.
> 
> When using the optional operator argument, the function will return [true](https://www.php.net/manual/en/reserved.constants.php#constant.true) if the relationship is the one specified by the operator, [false](https://www.php.net/manual/en/reserved.constants.php#constant.false) otherwise.
https://www.php.net/manual/en/function.version-compare.php
> 8.1.0: Der Parameter num_points ist veraltet und sollte  nicht mehr verwendet werden.
https://www.php.net/manual/de/function.imagefilledpolygon.php

Thumbnail: Fix wrong if condition

---

build/optimize_build.php

Fixes "Implicitly marking a parameter as nullable is deprecated since PHP 8.4. Update the type to be explicitly nullable instead. Found implicitly nullable parameter: $filter."
This was for whatever reason removed in a previous commit.
https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

Update optimize_build.php to fix "Implicitly marking a parameter as nullable is deprecated"

---

application/modules/admin/config/config.php

- Add row for admin module in modules table and restore admin module boxes if missing.
The entry for the admin module was missing if it wasn't a fresh 2.2.7 install. Therefore on the update to 2.2.7 the boxes for the admin module looked orphaned and got deleted. Without the entries for these boxes in the modules_boxes_content table it is impossible to add these boxes to the menu. Already existing boxes can be used until they are manually deleted from the menu.

Add row for admin module and restore boxes

---

application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/layouts/settings.php

- Use arrows for the order of the module data.
Previously "ASC" and "DESC" was displayed, which is not intuitive for a user. From left to right or from right to left is better in this case.

Admin: Use arrows for the order of module data

---

application/modules/admin/config/config.php

- Remove failed module install leftovers
There was a bug, which caused installs of modules with folderrights to fail. Therefore there might be leftovers in the database.
Call the uninstall function for known affected modules to remove possible leftovers if needed. This might be the case if the module is present as not installed.

Remove failed module install leftovers

---

application/libraries/Ilch/Upload.php
tests/libraries/ilch/UploadTest.php

- Add some unit tests for the upload class.
- Update Upload.php to deprecate functions
The upload class will be replaced after some time by #1162
See also:
https://github.com/IlchCMS/Ilch-2.0/pull/1162
Fixes https://github.com/IlchCMS/Ilch-2.0/issues/809

Create UploadTest and deprecate parts of Upload class.php

---

application/modules/awards/config/config.php
application/modules/awards/controllers/admin/Index.php
application/modules/awards/controllers/admin/Settings.php
application/modules/awards/translations/de.php
application/modules/awards/translations/en.php
application/modules/awards/views/admin/settings/index.php

- Add user notification for receiving an award (either as user or team).
- Add option to disable the user notification. By default it is enabled.
#438

Awards: Add user notification

---

application/modules/teams/config/config.php
application/modules/teams/controllers/admin/Index.php
application/modules/teams/controllers/admin/Settings.php
application/modules/teams/translations/de.php
application/modules/teams/translations/en.php
application/modules/teams/views/admin/settings/index.php

- Added a notification for users added to a team. By default enabled.
- Added an option to disable this feature.
Fixes #438

Teams: Add user notification for users added to a team.

---

.github/workflows/ci.yaml

- Update CI workflow to test with MySQL and MariaDB.
The tests with **MariaDB** currently only **run with PHP 8.4** to keep the number of variants that need to run lower. Otherwise the number of variants would be 18 instead of 8.
All tests run as previously with **MySQL 5.7** and **all supported PHP versions**.
Currently we don't run tests with **MySQL greater than 5.7** as they **would fail**.
#1180

Update CI workflow to test with MySQL and MariaDB

---

application/modules/training/config/config.php
application/modules/training/controllers/Index.php

Behenbt den Fehler : "foreach() argument must be of type array|object, null given in"

Training v1.10.1

---

.github/workflows/ci.yaml

- Add the latest version of MariaDB to the CI workflow.
- Use mariadb-admin instead of mysqladmin where required.
mysqladmin is no longer known in the official docker image of MariaDB 11 and newer.
> 11.0, unlike previous version, no longer includes mysql named compatible executable symlinks inside the container. 
https://mariadb.com/kb/en/mariadb-11-0-1-release-notes/#docker-official-images
https://jira.mariadb.org/browse/MDEV-29582

CI workflow: Add MariaDB latest

---

application/modules/admin/views/admin/menu/index.php

- Fix the selection of user groups for the "not visible for" setting of a menu item.
Fixes #1198

Menu: Fix selecting of user groups

---

application/modules/user/mappers/User.php
application/modules/user/models/User.php

Non null default values caused them to get deleted. If the default value of the first name for example was an empty string then the field array with the index "first_name" was considered set and the empty first name was saved to the database.
Unrelated to the issue: Don't store values from the model in extra variables. Just use the model.
Fixes #1205
#1204

User model: Non null default values caused them to get deleted

---

application/modules/downloads/config/config.php
application/modules/downloads/controllers/Index.php
application/modules/downloads/controllers/admin/Downloads.php
application/modules/downloads/controllers/admin/Index.php
application/modules/downloads/mappers/Downloads.php
application/modules/downloads/mappers/File.php
application/modules/downloads/models/DownloadsItem.php
application/modules/downloads/models/File.php
application/modules/downloads/views/admin/downloads/treatdownloads.php
application/modules/downloads/views/admin/index/index.php
application/modules/downloads/views/index/index.php
application/modules/downloads/views/index/show.php

- Removed the unused column "downloads_id" of the "downloads_items" table. This one always had the value 1.
- Changed the data type of the "type" column in the "downloads_items" table from "INT(11)" to "TINYINT(1)".
- Changed the data type of the "cat" column in the "downloads_files" table from "MEDIUMINT(9)" to "INT(11)". Relation with id column of the downloads_items table.
- Renamed the column "cat" to "item_id".
- Changed the data type of the "file_id" column in the "downloads_files" table from "VARCHAR(150)" to "INT(11)". Relation with id column of the media table. See also: https://github.com/IlchCMS/Ilch-2.0/issues/879
- Delete (orphaned) rows with an "item_id" that does not exist in the "downloads_items" table.
- Added a FKC to the "downloads_files" table.
- Renamed several …

Downloads: Various improvements

---

application/modules/birthday/config/config.php
application/modules/birthday/controllers/Birthdays.php

- Fix date format for the date validator
The date from fullcalendar is like this:
2025-04-28T00:00:00+02:00
Cherry picked from this branch:
https://github.com/IlchCMS/Ilch-2.0/compare/birthday-fixes-issue1213?expand=1

Birthday: Fix date format for the date validator

---

application/libraries/Ilch/Layout/Helper/GetMenu.php
application/libraries/Ilch/Layout/Helper/GetMenus.php
application/libraries/Ilch/Layout/Helper/Menu/Mapper.php
application/libraries/Ilch/Layout/Helper/Menu/Model.php

- Remove dead code from buildMenu function.
- Other smaller changes.
Removed code like below for the link and span class. Unit tests still pass.
```
...
// link classes
if ($parentType === $menuData['items'][$itemId]::TYPE_MENU || array_dot($options, 'menus.a-class')) {
$aClasses[] = array_dot($options, 'menus.a-class');
} else {
$aClasses[] = array_dot($options, 'menus.a-class');
}
...
```

Remove dead code from buildMenu function

---

application/libraries/Ilch/Upload.php

- Thumbnail creation fails with ico images
- Don't create a thumbnail if the image is already thumbnail size.

Thumbnail creation fails with ico images

---

application/modules/admin/config/config.php

- Remove deletion of translation.umd.js
Couldn't find that file in the last releases and the path was wrong.

Remove deletion of translation.umd.js

---

.github/workflows/ci.yaml
tests/PHPUnit/Ilch/DatabaseTestCase.php

- Make sure table names are quoted by backticks by using the drop function of the QueryBuilder.
- GitHub CI: Test with latest MySQL and limit jobs
Limit jobs needed to be run by only testing with oldest and newest supported PHP version.
We previously ran 8 jobs. This would have increased to at least 14 (all PHP versions and MySQL 5.7 and latest).
Thanks to @PrivatePHPCoder for finding the cause of the issue https://github.com/IlchCMS/Ilch-2.0/issues/1201#issuecomment-2902169517
The unit tests failed because since MySQL 8.0 "groups" is a reserved word:
https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-8-0-G
Fixes #1201

GitHub CI: Test with latest MySQL and limit jobs
