application/modules/admin/static/css/admin.css
application/modules/admin/views/admin/settings/index.php
application/modules/admin/views/admin/settings/maintenance.php

radio button with new flip style

radio button with new flip style

---

application/modules/guestbook/views/admin/settings/index.php

radio button adapted to the new flip style

radio button adapted to the new flip style

---

application/modules/admin/static/css/admin.css
application/modules/imprint/views/admin/settings/index.php
application/modules/jobs/views/admin/index/treat.php
application/modules/linkus/views/admin/settings/index.php
application/modules/user/views/admin/settings/index.php

radio button adapted to the new flip style; update user settings

radio button adapted to the new flip style; update user settings

---

application/modules/newsletter/config/config.php
application/modules/newsletter/controllers/admin/Index.php
application/modules/newsletter/controllers/admin/Settings.php
application/modules/newsletter/mappers/Newsletter.php
application/modules/newsletter/translations/de.php
application/modules/newsletter/translations/en.php
application/modules/newsletter/views/admin/settings/index.php
application/modules/user/config/config.php
application/modules/user/controllers/Panel.php
application/modules/user/mappers/User.php
application/modules/user/models/User.php
application/modules/user/static/css/user.css
application/modules/user/translations/de.php
application/modules/user/translations/en.php
application/modules/user/views/panel/setting.php

es hat sehr lange gedauert für die paar Zeilen ....
- Radiobutton angepasst an Adminbereich in den User Settings
- User können in den Setting simple den Newsletter ein und ausmachen.
- Übersicht der Empfänger im Adminbereich eingebaut. (Ist der User registriert wird sein Name mit angezeigt, andernfalls nur die Mail)
hab die anderen Änderungen erstmal wieder raus genommen, dass man einzelne User aus der Newsletter auswählen kann, um nicht an alle eingetragenen zu schicken.

User Modul Newsletter

---

application/libraries/Ilch/Transfer.php
application/modules/admin/controllers/admin/Update.php

The key-part of this small pull request is the reduction of HTTP GET requests of the Ilch-updater.
[Reduce HTTP GET requests (Ilch-updater)](https://github.com/IlchCMS/Ilch-2.0/commit/b5868e4b2d43e8e00d7585b1650c06f5d5e3b2c7)
As addition to that the Ilch-updater now deletes the associated update-files after installing the update.
On click on the update-function it switched to the download-icon. Now
always show the refresh-icon for the update feature.

Reduce HTTP GET requests (Ilch-updater) and more

---

application/modules/user/views/login/index.php

The inline help was overlapping with the input-boxes.

Fix the inline help on the login-page

---

application/modules/user/controllers/Panel.php

Try to crop the avatar image if it is needed. Don't try to crop the
image if it would probably require too much memory.

Crop avatar if necessary

---

application/modules/forum/views/showtopics/index.php

Fix undefined variable: userAccess in
application/modules/forum/views/showtopics/index.php on line 112
This error occured when trying to view a forum as a guest.

Fix undefined variable: userAccess

---

application/modules/guestbook/translations/de.php
application/modules/guestbook/translations/en.php
application/modules/guestbook/views/index/newentry.php
application/modules/link/controllers/admin/Index.php
application/modules/link/translations/de.php
application/modules/link/translations/en.php
application/modules/link/views/admin/index/treatLink.php

Use the validation-class in the link-module to validate the name, link and banner.

Use validation-class in link-module

---

application/libraries/Ilch/Layout/Frontend.php

`<?= $this->getBox('user', 'login', 'login.navbar'); ?>`
Die normale Loginbox im Menü bleibt dadurch intakt.

Layouts/Boxes: getBox() accepts a custom view file

---

application/modules/admin/controllers/admin/Index.php
application/modules/admin/mappers/Module.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/index/index.php

Add some information to the admincenter-startpage.
Awaiting unlocking for
- guestbook-entries
- partner-entries
Increased cell-width so that the translation doesn't get wrapped.

Add some information to admincenter-startpage

---

application/modules/admin/controllers/admin/Index.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/index/index.php
application/modules/user/mappers/User.php

Added users awaiting approval, which was suggested in the last pull-request.
Changed the translation from "unlocking" to "approval".

Add users awaiting approval

---

application/modules/awards/views/admin/index/index.php

Just adding escaping of the award or the returnvalue of getEvent()
http://redmine.ilch2.de/issues/312

Escape getEvent - ticket312

---

application/modules/partner/boxes/views/partner.php

Uncaught TypeError: Cannot read property 'top' of undefined
This was the case with an "empty" partner-box.

Fix uncaught typeError

---

application/libraries/Ilch/Design/Base.php
application/libraries/Ilch/Functions.php
application/modules/user/config/config.php
application/modules/user/controllers/Login.php
application/modules/user/controllers/Panel.php
application/modules/user/controllers/admin/Group.php
application/modules/user/controllers/admin/Index.php
application/modules/user/controllers/admin/Profilefields.php
application/modules/user/controllers/admin/Providers.php
application/modules/user/controllers/admin/Settings.php
application/modules/user/mappers/AuthProvider.php
application/modules/user/models/AuthProviderModule.php
application/modules/user/models/AuthProviderUser.php
application/modules/user/models/Provider.php
application/modules/user/service/Password.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php
application/modules/user/views/admin/providers/edit.php
application/modules/user/views/admin/providers/index.php
application/modules/user/views/login/index.php
application/modules/user/views/panel/providers.php
application/modules/user/views/panel/settings.php
static/css/ilch.css

Eine erste Implementierung für Twitter kommt zügig. Ohne diese Implementierung, kann man mit diesem hier noch nicht viel anfangen, ist halt nur die Basis.
Wichtig:
Neuer SQL Code in der config.php vom user module.

Implements an authentication providers interface

---

application/modules/user/translations/de.php
application/modules/user/translations/en.php
application/modules/user/views/regist/confirm.php

http://redmine.ilch2.de/issues/324

User-module: Add missing translation

---

application/modules/forum/views/admin/index/index.php
application/modules/gallery/translations/de.php
application/modules/gallery/translations/en.php
application/modules/gallery/views/admin/index/index.php

http://redmine.ilch2.de/issues/322

Gallery-module: Add missing translation

---

application/modules/install/controllers/Index.php
application/modules/install/translations/de.php
application/modules/install/translations/en.php
application/modules/install/views/index/database.php

Database select falls back to an text input, if no database found.

Fixes install flow with skip-show-database enabled

---

application/modules/awards/controllers/admin/Index.php
application/modules/awards/translations/de.php
application/modules/awards/translations/en.php
application/modules/awards/views/admin/index/treat.php

Validation::setCustomFieldAliases() scheint noch nicht zu funktionieren.
Wo ist der Fehler?
> utId was not filled out.
typ was not filled out.
http://redmine.ilch2.de/issues/313

Awards-module: add validation

---

application/modules/awards/controllers/admin/Index.php

Only create an instance of AwardsModel if the post-data is valid. The
instance is only needed in this case.

Move creation of instance of AwardsModel

---

application/modules/install/controllers/Index.php
application/modules/install/views/index/systemcheck.php

http://redmine.ilch2.de/issues/332

Check if the root-path is writable

---

application/modules/statistic/controllers/Index.php

Notice: Undefined variable: modulesMapper in
application/modules/statistic/controllers/Index.php on line 154

Fix typo in statistic-module

---

application/modules/comment/controllers/admin/Settings.php
application/modules/comment/views/admin/settings/index.php

Currently the min-Validator fails, but it should work as expected when http://redmine.ilch2.de/issues/347 is fixed.

Use validation-class in comment-module for the settings

---

application/modules/away/views/admin/index/index.php
application/modules/away/views/index/index.php

http://www.ilch.de/forum-showposts-53495.html

Escape getText() and getReason()

---

application/modules/war/views/admin/ajax/game.php
application/modules/war/views/admin/enemy/index.php
application/modules/war/views/admin/group/index.php
application/modules/war/views/admin/index/index.php
application/modules/war/views/admin/index/treat.php
application/modules/war/views/group/index.php
application/modules/war/views/index/index.php
application/modules/war/views/index/show.php

Further changed input type to number for the result of the war (in other
words the points of the team and the enemy).

War-module: add escaping

---

application/modules/war/views/group/show.php

Schneller gemerged als ich den Commit noch nachschieben konnte. :D
Sorry.

Add escaping to group-show

---

application/modules/away/controllers/Index.php
application/modules/away/translations/de.php
application/modules/away/translations/en.php
application/modules/away/views/index/index.php

http://redmine.ilch2.de/issues/350

Away-module: use the validation-class

---

application/modules/downloads/controllers/Index.php
application/modules/gallery/controllers/Index.php
application/modules/user/controllers/Gallery.php

http://redmine.ilch2.de/issues/344

Add redirect to fix ticket 344 for other comments, too

---

application/libraries/Ilch/Validation.php

http://redmine.ilch2.de/issues/347

Fix issue with min:0 and max:0

---

application/modules/away/controllers/Index.php
application/modules/away/translations/de.php
application/modules/calendar/views/index/index.php

http://redmine.ilch2.de/issues/351
- validate calendarShow
- Escape getReason() in view of calendar

Away-module: validate calendarShow

---

application/modules/guestbook/controllers/admin/Settings.php
application/modules/guestbook/translations/en.php
application/modules/guestbook/views/admin/settings/index.php

http://redmine.ilch2.de/issues/352
- Use validation-class for settings
- Fixed translation

Guestbook-Module: Use validation-class for settings

---

application/modules/calendar/views/admin/index/index.php
application/modules/calendar/views/index/index.php
application/modules/events/views/admin/index/index.php
application/modules/events/views/show/event.php

Bitte prüfen ob das Probleme mit Google Maps macht, weil ich das nicht testen konnte.

Escape various strings in calendar- and events-module

---

application/modules/comment/mappers/Comment.php

http://redmine.ilch2.de/issues/349

Delete child-comments if parent-comment got deleted

---

application/libraries/Ilch/Upload.php
application/modules/admin/layouts/index.php
application/modules/admin/views/admin/index/index.php
application/modules/forum/views/index/index.php
application/modules/forum/views/showposts/index.php
application/modules/forum/views/showtopics/index.php
application/modules/shoutbox/boxes/views/shoutbox.php
application/modules/shoutbox/views/admin/index/index.php
application/modules/shoutbox/views/index/index.php
application/modules/user/views/panel/dialog.php
application/modules/user/views/panel/dialogviewmessage.php

guessRequiredMemory() needs to be public as it is used in the
events-module.

Escape mostly user-names

---

application/modules/admin/views/admin/modules/index.php
application/modules/admin/views/admin/modules/search.php

In addition to this fixed a typo in phpExtensions.

Check requirements on list of installed modules

---

application/modules/admin/controllers/admin/Backup.php
backups/index.php

Add random string to backup-filename
Add index.html to prevent index listing of the backups-folder
http://redmine.ilch2.de/issues/354

Add random string to backup-filename

---

application/modules/user/controllers/Regist.php
application/modules/user/mappers/User.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php

- Use stronger confirmedCode
- Remove getUserByConfirmedCode()
- Added translation

registration confirm improvements

---

application/modules/user/controllers/Login.php

- Fix the redirects
- Don't trim password-fields

Fix redirects newpasswordAction

---

application/libraries/Ilch/Translations/de.php
application/libraries/Ilch/Translations/en.php
application/modules/statistic/controllers/Index.php
application/modules/statistic/views/index/index.php
application/modules/statistic/views/index/online.php
application/modules/statistic/views/index/show.php

Add translations of month and weekday to statistic-module

---

application/modules/newsletter/views/admin/index/index.php
application/modules/newsletter/views/admin/receiver/index.php

http://redmine.ilch2.de/issues/370

Ticket 370 - Escape username, subject and mail-address

---

development/vagrant/scripts/install.sh

Läuft nun problemlos bei mir durch.

Fixes curl not found when setting up your vagrant box (#368)

---

application/modules/admin/controllers/admin/Page.php

http://www.ilch.de/forum-showposts-53559.html

Fix permaLink after invalid input

---

application/modules/forum/mappers/Forum.php
application/modules/forum/mappers/Topic.php

http://redmine.ilch2.de/issues/377

Delete topics and posts if forum gets deleted in admincenter

---

application/modules/newsletter/controllers/admin/Index.php
application/modules/newsletter/translations/de.php
application/modules/newsletter/translations/en.php
application/modules/newsletter/views/admin/index/treat.php

http://redmine.ilch2.de/issues/369

Use validation-class when writing a newsletter

---

application/modules/newsletter/controllers/Index.php

http://redmine.ilch2.de/issues/378

Newsletter-module: create selector and confirmCode for users

---

application/modules/shoutbox/boxes/views/shoutbox.php
application/modules/shoutbox/translations/de.php
application/modules/shoutbox/translations/en.php

http://redmine.ilch2.de/issues/380
http://redmine.ilch2.de/issues/381

Translate error-message and set name-input to readonly for users

---

application/modules/shoutbox/boxes/Shoutbox.php

http://redmine.ilch2.de/issues/382

Shoutbox-module - add serverside validation (ticket 382)

---

application/modules/events/controllers/admin/Settings.php
application/modules/events/views/admin/settings/index.php

http://redmine.ilch2.de/issues/385

Use validation-class for events-module settings (ticket 385)

---

application/modules/article/controllers/admin/Index.php

http://redmine.ilch2.de/issues/384

Article-Module: delete comments in deleteAction()

---

application/modules/events/controllers/Index.php
application/modules/events/translations/de.php
application/modules/events/translations/en.php
application/modules/events/views/index/treat.php

http://redmine.ilch2.de/issues/387

Use validation-class for event creation/editing

---

application/modules/user/controllers/Login.php
application/modules/user/controllers/Panel.php
application/modules/user/controllers/Regist.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php
application/modules/user/views/login/newpassword.php
application/modules/user/views/panel/password.php

- Use validation-class for passwords or fix usage of it
- Fixed translation

Use validation-class for passwords or fix usage of it

---

application/modules/cookieconsent/controllers/admin/Index.php
application/modules/cookieconsent/views/admin/index/index.php

[Ticket 402](http://redmine.ilch2.de/issues/402)

Use the validation-class for the cookieconsent-module

---

application/modules/imprint/controllers/admin/Index.php
application/modules/imprint/views/admin/index/index.php

`'email'     => 'email'`
ist bis jetzt die einzige Regel.
Ist jetzt die Frage ob und wenn ja welche Felder man z.B. auf required setzen möchte und vermutlich auch in Abhängigkeit davon ob imprintStyle auf "Privat" oder "Firma" steht?
Außerdem kann es da je nach Land auch andere Voraussetzungen geben.

Use the validation-class for the imprint-module

---

application/modules/statistic/config/config.php
application/modules/statistic/controllers/Index.php
application/modules/statistic/controllers/admin/Index.php
application/modules/statistic/translations/de.php
application/modules/statistic/translations/en.php
application/modules/statistic/views/admin/index/index.php
application/modules/statistic/views/index/index.php

http://redmine.ilch2.de/issues/254

Statistic-module: add settings to hide parts of the statistic

---

application/modules/events/controllers/Index.php

http://www.ilch.de/forum-showposts-53654.html

Events-module: fix wrong startTime

---

application/modules/user/config/config.php
application/modules/user/controllers/Panel.php
application/modules/user/views/panel/setting.php

http://redmine.ilch2.de/issues/406

Fix optMail-setting not being saved (ticket 406)

---

application/modules/user/controllers/Panel.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php
application/modules/user/views/panel/profile.php

http://redmine.ilch2.de/issues/360

Use validation class for profileAction()

---

application/modules/media/static/js/script.js
application/modules/user/controllers/admin/Profilefields.php

- Add "saveSuccess"-message when modifying a profile field.
- Random comment fix unrelated to the profile field feature.
http://www.ilch.de/forum-showposts-53677.html

Show success-message on profilefield edit

---

application/libraries/Ilch/Transfer.php
application/modules/admin/views/admin/index/index.php
application/modules/admin/views/admin/settings/update.php

Update a few URLs as the controller and/or the action changed.
Call class_exists() to check if the configClass exists and
method_exists() to make sure getUpdate() is existing before trying to
call it.

Fix some issues in the ilch-updater

---

application/libraries/Ilch/Transfer.php
application/modules/admin/controllers/admin/Layouts.php
application/modules/admin/controllers/admin/Modules.php
application/modules/admin/controllers/admin/Settings.php

Some proposed changes:
Verifying and if invalid deleting downloaded files are now done in save().
Used Try ... Finally to make sure the verification is done.
Removed clean-up code in updateAction() as this is already done in update().

Small refactoring of the updater

---

application/libraries/Ilch/Transfer.php
application/modules/admin/controllers/admin/Modules.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php

- Handle a defect, but signed zip-file
- Display state of modules correctly even if some errors occured

Fix some bugs in module-update

---

application/modules/admin/controllers/admin/Layouts.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/layouts/index.php
application/modules/admin/views/admin/layouts/search.php

- Handle a defect, but signed zip-file
- Display state of layouts correctly even if some errors occured

Fix some bugs in layout-update

---

application/modules/user/controllers/admin/Group.php
application/modules/user/controllers/admin/Index.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php

http://redmine.ilch2.de/issues/411

Force the user-group as default one for a new user

---

application/modules/teams/views/index/index.php

http://redmine.ilch2.de/issues/419

Show Leader/CoLeader even if group of team is empty

---

application/libraries/Ilch/Redirect.php

To switch from backend to frontend:
->to(['controller' => 'Foo', 'action' => 'bar'], 'frontend');
The inverse:
->to(['controller' => 'Foo', 'action' => 'bar'], 'admin');
Blank for default behavior:
->to(['controller' => 'Foo', 'action' => 'bar']);

Adds the possibility to redirect from backend to frontend

---

application/modules/awards/translations/de.php
application/modules/awards/translations/en.php
application/modules/awards/views/admin/index/index.php
application/modules/awards/views/index/index.php

http://redmine.ilch2.de/issues/422

Fix error in awards-module if team was deleted

---

application/modules/admin/views/admin/modules/notinstalled.php
application/modules/admin/views/admin/modules/show.php

- Added check for phpVersion and ilchCore to the notinstalled-view
- Added check for phpVersion, ilchCore and the dependencies to the show-view

Add missing checks to show- and notinstalled-view

---

application/modules/admin/mappers/Notifications.php
tests/modules/admin/mappers/NotificationsTest.php

- Return the id of last inserted row in addNotification()
- Check if addNotification() returns the expected id in the unit-test

Return id of last inserted row in addNotification()

---

application/libraries/Ilch/Accesses.php
application/modules/admin/controllers/admin/Modules.php
application/modules/admin/mappers/Module.php
application/modules/admin/views/admin/modules/index.php

Fatal error: Uncaught Error: [] operator not supported for strings in
application\libraries\Ilch\Accesses.php:73
PHP 7.1

Fix uncaught error: [] operator not supported

---

application/libraries/Ilch/Layout/Helper/Menu/Model.php

http://www.ilch.de/forum-showposts-53592-p2.html#388999

Reduce queries needed for the menu in the frontend

---

application/modules/cookieconsent/controllers/admin/Index.php

http://www.ilch.de/forum-showposts-53781.html

fix errors in cookieconsent

---

application/modules/war/views/admin/enemy/index.php

enemy image display fixed

---

application/modules/forum/controllers/Shownewposts.php
application/modules/forum/translations/de.php
application/modules/forum/translations/en.php
application/modules/forum/views/index/index.php

Forum: Alle Foren als gelesen markieren

Feature #532

---

application/modules/admin/boxes/Layoutswitch.php
application/modules/admin/boxes/views/layoutswitch.php
application/modules/admin/controllers/admin/Layouts.php
application/modules/admin/views/admin/settings/index.php

Config "Default Layout" is Default in Dropdown list
Check of Directory

Fix Layout List/Box

---

application/modules/birthday/views/index/index.php

https://www.ilch.de/index.php?forum-showposts-54829-p1#395534

Fix: Birthday-Modul wrong birthday on 1.1.

---

application/libraries/Ilch/Accesses.php

Fix accesses on lower PHP-Versions

---

application/modules/article/controllers/Cats.php

https://www.ilch.de/forum-showposts-55201-p1.html

Article: Fix ID verification Query

---

application/modules/training/boxes/Nexttraining.php
application/modules/training/boxes/views/nexttraining.php
application/modules/training/config/config.php
application/modules/training/controllers/Index.php
application/modules/training/controllers/Trainings.php
application/modules/training/controllers/admin/Index.php
application/modules/training/controllers/admin/Settings.php
application/modules/training/mappers/Entrants.php
application/modules/training/mappers/Training.php
application/modules/training/models/Entrants.php
application/modules/training/models/Training.php
application/modules/training/static/css/style.css
application/modules/training/translations/de.php
application/modules/training/translations/en.php
application/modules/training/views/admin/index/treat.php
application/modules/training/views/admin/settings/index.php
application/modules/training/views/index/show.php

See: [https://www.ilch.de/index.php?forum-showposts-56399-p1](url)

add Box for Training-Modul

---

application/modules/user/controllers/Panel.php
application/modules/user/views/panel/settings.php

[https://www.ilch.de/forum-showposts-56467.html#401051](url)

Hide social media when empty

---

application/libraries/Ilch/Translations/de.php
application/libraries/Ilch/Translations/en.php
application/libraries/Ilch/Validation.php
application/libraries/Ilch/Validation/Validators/Date.php
tests/libraries/ilch/Validation/Validators/DateTest.php

add Parameter to Date-Validators

---

application/modules/downloads/config/config.php
application/modules/downloads/mappers/File.php
application/modules/downloads/views/index/index.php

https://www.ilch.de/forum-showposts-56637-p1.html#401539

Downloads-Modul: Fix Error on empty Download

---

application/modules/user/controllers/Panel.php
application/modules/user/views/panel/profile.php

See: https://www.ilch.de/index.php?forum-showposts-56658-p1#401622

FIX: Error on update hidden profile fields

---

application/libraries/Ilch/Accesses.php
application/libraries/Ilch/Database/Mysql/QueryBuilder.php
application/modules/admin/config/config.php
application/modules/admin/controllers/admin/Boxes.php
application/modules/admin/controllers/admin/Modules.php
application/modules/admin/controllers/admin/Page.php
application/modules/admin/mappers/Box.php
application/modules/admin/mappers/Page.php
application/modules/article/controllers/admin/Index.php
application/modules/user/controllers/admin/Group.php
application/modules/user/mappers/Group.php
application/modules/user/views/profil/index.php

Updates all group access + Add group access when creating

---

application/modules/article/controllers/admin/Index.php

https://www.ilch.de/index.php?forum-showposts-56775-p1#401953

Article -> Fix Error on set "AccessData"

---

application/libraries/Ilch/Layout/Helper/GetMenu.php
application/libraries/Ilch/Layout/Helper/Menu/Model.php
tests/libraries/ilch/Layout/Helper/GetMenuTest.php

Die getMenu Funktion kann mit 3 Parametern aufgerufen werden.
$this->getMenu( MenuID , 'Template' , 'Options(Array) ')
Dieser Commit beinhaltet eine Änderung des 3. Parameters -> Options-Array.
Es ist nun auch möglich dem ArrayKey "a-class" eine eigene Klasse mitzugeben.
Hier geben wir z.B. dem Key 'a-class' die Klasse 'nav-link' mit
Beispiel:
```
getMenu(1,
'%c', [
'menus' => [
'ul-class-root' => 'navbar-nav',
'li-class-root' => 'nav-item',
**'a-class' => 'nav-link',**   <<<<<< ------------------
'allow-nesting' => false
],
'boxes' => [
'render' => false
],
]);
```
Beim Aufruf ohne Options werden die Ilch Standard-Klassen verwendet.
```
DEFAULT_OPTIONS = [
'menus' => [
'ul-class-root' => 'list-unstyled ilch_menu_ul',
'ul-class-child' => 'list-unstyled ilch_menu_ul',
'li-class-root' => …
```

Kleines Update der getMenu() Funktion

---

application/modules/article/controllers/admin/Index.php
application/modules/user/service/Login.php

Update wrong datetime format

---

application/libraries/Ilch/Config/Database.php
application/libraries/Ilch/Controller/Base.php
application/libraries/Ilch/Database/Mysql.php
application/libraries/Ilch/Database/Mysql/Select.php
tests/libraries/ilch/Database/Mysql/SelectTest.php
tests/libraries/ilch/RouterTest.php

Klammer Benutzung: SELECT (anzahl1 + anzahl) as summe FROM `[prefix]_Test`
a.* Support: SELECT a.* FROM `[prefix]_Test` as `a`

Update Tester + Klammer Benutzung + a.* Support

---

application/libraries/Captcha/DefaultCaptcha.php
application/libraries/Captcha/GoogleCaptcha.php
application/libraries/Ilch/Translations/de.php
application/libraries/Ilch/Translations/en.php
application/libraries/Ilch/Validation.php
application/libraries/Ilch/Validation/Validators/Captcha.php
application/libraries/Ilch/Validation/Validators/Grecaptcha.php
application/modules/admin/config/config.php
application/modules/admin/controllers/admin/Settings.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/settings/index.php
application/modules/contact/controllers/Index.php
application/modules/contact/views/index/index.php
application/modules/guestbook/config/config.php
application/modules/guestbook/controllers/Index.php
application/modules/guestbook/views/index/newentry.php
application/modules/partner/config/config.php
application/modules/partner/controllers/Index.php
application/modules/partner/views/index/index.php
application/modules/teams/config/config.php
application/modules/teams/controllers/Index.php
application/modules/teams/views/index/join.php
application/modules/user/config/config.php
application/modules/user/controllers/Regist.php
application/modules/user/views/regist/input.php

Optionale Einbindung des GoogleCaptcha V2/3
Fixes #510

opt GoogleCaptcha V2/V3 einbindung

---

application/modules/user/controllers/Panel.php
application/modules/user/mappers/Dialog.php
application/modules/user/static/css/message.css
application/modules/user/views/panel/dialog.php

Fügt die Möglichkeit hinzu Private Nachrichten Dialoge zu löschen.

Add option to delete private messages

---

application/modules/admin/config/config.php
application/modules/checkoutbasic/config/config.php
application/modules/teams/config/config.php
index.php

A pull request for a few needed fixes for an update.
- Update ilch version number (2.1.43 right?)
- Replace vendor folder on update
- A few fixes to updated modules
Notes:
- A version 1.19.1 of the teams module was never released? So replaced that with an "1.19.0" case
- Checkoutbasic was missing a few cases for previous versions.

Few fixes as preparation for an update

---

application/libraries/Ilch/Transfer.php

Remove usage of the deprecated procedural API of the ZIP functions and replace it with the usage of the ZipArchive class.
See:
https://www.php.net/manual/en/class.ziparchive.php
https://www.php.net/manual/en/ref.zip.php
Fixes #538

Issue 538: Remove usage of deprecated procedural ZIP API

---

application/modules/user/views/admin/profilefields/treat.php

Fixes "Adding another translation to an existing profile field fails."
Fixes #547

Fix issue 547

---

application/modules/admin/controllers/admin/Settings.php
application/modules/admin/layouts/login.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/settings/mail.php
application/modules/install/views/index/configuration.php
application/modules/statistic/views/index/index.php
application/modules/user/boxes/views/login.php
application/modules/user/controllers/Panel.php
application/modules/user/mappers/NotificationPermission.php
application/modules/user/views/login/index.php
application/modules/user/views/login/newpassword.php
application/modules/user/views/panel/index.php
application/modules/user/views/panel/notifications.php
application/modules/user/views/panel/password.php
application/modules/user/views/regist/input.php
tests/modules/user/mappers/NotificationPermissionTest.php

- Improve mail settings by adding some hints and hiding irrelevant settings
- Added autocomplete to login input fields
- HTTPS instead of HTTP in a link to ilch.de in the statistic module
- Added getPermissionsByUserId() and fixed some issues in the user notifications
https://www.chromium.org/developers/design-documents/create-amazing-password-forms
https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields

Improve mail settings and more

---

application/libraries/Ilch/Layout/Frontend.php
application/modules/statistic/boxes/Online.php
application/modules/statistic/boxes/Stats.php
application/modules/statistic/config/config.php
application/modules/statistic/controllers/Index.php
application/modules/statistic/controllers/admin/Index.php
application/modules/statistic/mappers/Statistic.php
application/modules/statistic/models/Statistic.php
application/modules/statistic/plugins/languageCodes.php
application/modules/statistic/translations/de.php
application/modules/statistic/translations/en.php
application/modules/statistic/views/index/index.php
index.php

Update Copyrights Hints
Use DB-Mapper
Update / Add new OS (Old USER_AGENT)
Add User-Agent Client Hints
Fix BoxMapper
Fixes #485

Statistic-Module

---

application/libraries/Ilch/Database/Mysql.php
application/libraries/Ilch/Date.php
application/libraries/Ilch/Design/Base.php
application/modules/admin/config/config.php
application/modules/user/config/config.php

Fehler beim nächsten Updatet behoben

Fehler beim Update fix

---

application/modules/admin/views/admin/modules/notinstalled.php

Fehler wenn Update-Server nicht erreichbar

---

application/modules/article/views/admin/index/treat.php

https://www.ilch.de/index.php?forum-showposts-58305-p1#405739

Trying to access array offset on value of type null

---

application/modules/admin/config/config.php

Fix Error on install + add new updateserver

Fix Error on install + add new updateserver

---

application/libraries/Ilch/Layout/Helper/GetMedia.php
application/libraries/Ilch/Sorter.php
application/modules/admin/controllers/admin/Boxes.php
application/modules/admin/controllers/admin/Page.php
application/modules/admin/mappers/Box.php
application/modules/admin/mappers/Page.php
application/modules/admin/models/Box.php
application/modules/admin/models/Page.php
application/modules/admin/views/admin/boxes/index.php
application/modules/admin/views/admin/boxes/treat.php
application/modules/admin/views/admin/layouts/show.php
application/modules/admin/views/admin/page/index.php
application/modules/admin/views/admin/page/treat.php
application/modules/user/mappers/User.php

Layout Installation unter Show nicht möglich fix
gefunden von Ripper
Box & Page
Sortierfunktion hinzugefügt
Code Verbesserung

Layout Installation unter Show nicht möglich fix

---

application/modules/admin/models/Box.php

Fix Box Model

---

application/modules/faq/controllers/Index.php
application/modules/faq/controllers/admin/Cats.php
application/modules/faq/mappers/Category.php
application/modules/faq/mappers/Faq.php
application/modules/faq/models/Category.php
application/modules/faq/models/Faq.php
application/modules/faq/views/admin/index/index.php
application/modules/faq/views/admin/index/treat.php
application/modules/faq/views/index/index.php
application/modules/faq/views/index/show.php

**Am Beispiel des FAQ-Moduls**
Die Aufrufe der Models durch magische Methoden ersetzt.
- __contruct()
- __get()
- __set()
Dadurch weniger CodeZeilen im ganzen Modul
- in Controllern
- in Mappern
- in Views
Verzeichnisgröße NEU 46,5 KB
Verzeichnisgröße ALT 48,0 KB

Änderungen am QuellCode

---

application/modules/faq/controllers/Index.php
application/modules/faq/controllers/admin/Cats.php
application/modules/faq/mappers/Category.php
application/modules/faq/mappers/Faq.php
application/modules/faq/models/Category.php
application/modules/faq/models/Faq.php
application/modules/faq/views/admin/index/index.php
application/modules/faq/views/admin/index/treat.php
application/modules/faq/views/index/index.php
application/modules/faq/views/index/show.php

Revert "Änderungen am QuellCode"

---

development/bin/setup.sh

Bei einer Neuinstallation über Vagrant erscheint die Meldung : composer.phar: Permission denied

composer.phar: Permission denied

---

application/modules/user/translations/de.php
application/modules/user/translations/en.php

Revert removal of used translations and added missing translations for English.
https://github.com/IlchCMS/Ilch-2.0/commit/a31d2947a05e33b78b86b5702932ce9457d3fa32

Revert removal of used translations

---

composer.lock

New version of CKEditor

---

composer.lock

Update phpmailer and some other dependencies
PHPMailer 6.7.1 didn't made it into Ilch 2.1.44.

Update phpmailer and some other dependencies

---

application/modules/user/views/panel/profile.php

Fix "TypeError: Argument 1 passed to Ilch\Date::__construct() must be of the type string, null given"
https://www.ilch.de/forum-showposts-58507-p1.html#406695

Fix TypeError null given

---

.github/workflows/ci.yaml
application/modules/admin/config/config.php
application/modules/gallery/config/config.php
build/optimize_vendor.php

- Remove more files with optimize_vendor
- Updated ilchCore in the config.php of the gallery module. It requires a new file, which is part of Ilch 2.1.45.
- "replaceVendorDirectory"-Vorbereitung
- Run the tests on PHP 8.2 too.
Used parts of an earlier pull request by @hhunderter.
https://github.com/IlchCMS/Ilch-2.0/pull/607

Remove more files with optimize_vendor

---

application/modules/admin/controllers/admin/Modules.php

Error message was displayed in green instead of red.

Change message style

---

application/modules/calendar/config/config.php
application/modules/war/config/config.php

Change required PHP version. Should work just fine with PHP 7.3.

Change required PHP version

---

application/libraries/Ilch/Design/Base.php
application/libraries/Ilch/Redirect.php
application/libraries/Ilch/Request.php
application/modules/admin/controllers/Page.php
application/modules/admin/plugins/AfterDatabaseLoad.php
application/modules/article/plugins/AfterDatabaseLoad.php
application/modules/forum/plugins/AfterDatabaseLoad.php
application/modules/user/plugins/AfterDatabaseLoad.php

Fix für #579

---

application/libraries/Ilch/Design/Base.php
application/libraries/Ilch/Redirect.php
application/modules/admin/plugins/AfterDatabaseLoad.php
application/modules/article/plugins/AfterDatabaseLoad.php

Fix get on null in install. config is null during the installation.

Fix get on null in install

---

application/libraries/Ilch/Design/Base.php
application/libraries/Ilch/Layout/Helper/Menu/Model.php
application/libraries/Ilch/Redirect.php
application/modules/user/plugins/AfterDatabaseLoad.php

Dies sollte diese Fehler beheben:
Fixes #610 
Fixes #627 

Multilingual Settings Fix

---

application/modules/user/controllers/admin/Group.php

Beim Erstellen einer neuen Benutzergruppe wird der Fehler ausgegeben, wenn z.b. keine eigene Seiten vorhanden sind.

Fix foreach null array

---

application/libraries/Ilch/Functions.php
application/modules/calendar/config/config.php
application/modules/calendar/controllers/Events.php
application/modules/calendar/controllers/admin/Index.php
application/modules/calendar/mappers/Calendar.php
application/modules/calendar/mappers/Events.php
application/modules/calendar/models/Calendar.php
application/modules/calendar/translations/de.php
application/modules/calendar/translations/en.php
application/modules/calendar/views/admin/index/index.php
application/modules/calendar/views/admin/index/treat.php
application/modules/calendar/views/events/iCal.php
application/modules/calendar/views/events/index.php
application/modules/calendar/views/events/show.php
application/modules/calendar/views/index/index.php
tests/modules/calendar/_files/mysql_database.yml
tests/modules/calendar/mappers/CalendarTest.php

- An event longer than one day only got shown on the first day. For more details see the thread below:
https://www.ilch.de/forum-showposts-58538.html
- It looked like the recurring event feature didn't work. Changed the "repeat" function and the views.
- Added a feature to repeat an event until a specific date.
- Fixed the missing event description ("text") in the event details.
- Don't just show the end time, but the full date and time for an repetition of an event.
- Improved the UI for creating and editing an event.
- Fixed typos in translations
- Code style improvements
- Generate a UID according to the iCal specification and store it in the database as it has to be a persistent, globally unique identifier.
- https://www.rfc-editor.org/rfc/rfc5545#section-3.8.4.7
- Added the function …

Fix recurring events and multi day events

---

application/modules/awards/config/config.php
application/modules/birthday/boxes/views/birthday.php
application/modules/birthday/config/config.php
application/modules/birthday/controllers/Birthdays.php
application/modules/birthday/controllers/admin/Index.php
application/modules/calendar/boxes/views/calendar.php
application/modules/calendar/config/config.php
application/modules/calendar/views/admin/index/index.php
application/modules/calendar/views/index/index.php
application/modules/downloads/config/config.php
application/modules/downloads/views/admin/index/index.php
application/modules/link/config/config.php
application/modules/linkus/config/config.php
application/modules/partner/config/config.php
application/modules/user/config/config.php
application/modules/war/config/config.php

Fix "foreach() argument must be of type array|object, string given"
Further updated some more icons.
https://github.com/IlchCMS/Ilch-2.0/issues/635

Fix "foreach() argument must be of type array|object, string given"

---

composer.lock

Update CKEditor to 4.20.2
https://github.com/ckeditor/ckeditor4/blob/4.20.2/CHANGES.md#ckeditor-4202

Update CKEditor to 4.20.2

---

application/libraries/Ilch/Functions.php
application/libraries/Ilch/Transfer.php
application/modules/admin/config/config.php
application/modules/article/controllers/Index.php
application/modules/article/controllers/admin/Index.php
application/modules/article/views/admin/index/treat.php
application/modules/install/controllers/Index.php
application/modules/user/config/config.php
development/vagrant/scripts/install_phpmyadmin.sh

- Beim Update wird die Präfix nicht geändert.
- vendor-Ordner beim Update ersetzen.
- Add the function invalidateOpcache
- Artikel - Vorschau fehlten die Rechte

Various fixes before the release

---

composer.lock

Update FontAwesome to version 6.4.0
https://fontawesome.com/docs/changelog/

Update FontAwesome to version 6.4.0

---

application/modules/admin/views/admin/infos/folderrights.php

The "style" for the icon was applied to the link text

The "style" for the icon was applied to the link text

---

application/libraries/Ilch/Validation.php
application/libraries/Ilch/Validation/ErrorBag.php
application/libraries/Ilch/Validation/Validators/Base.php
application/libraries/Ilch/Validation/Validators/Captcha.php
application/libraries/Ilch/Validation/Validators/Date.php
application/libraries/Ilch/Validation/Validators/Email.php
application/libraries/Ilch/Validation/Validators/Exists.php
application/libraries/Ilch/Validation/Validators/Grecaptcha.php
application/libraries/Ilch/Validation/Validators/Integer.php
application/libraries/Ilch/Validation/Validators/Max.php
application/libraries/Ilch/Validation/Validators/Min.php
application/libraries/Ilch/Validation/Validators/Numeric.php
application/libraries/Ilch/Validation/Validators/Required.php
application/libraries/Ilch/Validation/Validators/Same.php
application/libraries/Ilch/Validation/Validators/Size.php
application/libraries/Ilch/Validation/Validators/Unique.php
application/libraries/Ilch/Validation/Validators/Url.php
tests/libraries/ilch/ValidationTest.php

- Fixed various warnings in the validator classes etc.
- Added some more unit tests.

Fixed various warnings in the validator classes

---

application/libraries/Ilch/Validation/Validators/Numeric.php

Fix invertErrorKey

---

application/modules/admin/static/js/codemirror/addon/comment/comment.js
application/modules/admin/static/js/codemirror/addon/comment/continuecomment.js
application/modules/admin/static/js/codemirror/addon/display/fullscreen.css
application/modules/admin/static/js/codemirror/addon/display/fullscreen.js
application/modules/admin/static/js/codemirror/addon/display/placeholder.js
application/modules/admin/static/js/codemirror/addon/edit/closebrackets.js
application/modules/admin/static/js/codemirror/addon/edit/matchbrackets.js
application/modules/admin/static/js/codemirror/addon/fold/brace-fold.js
application/modules/admin/static/js/codemirror/addon/fold/comment-fold.js
application/modules/admin/static/js/codemirror/addon/fold/foldcode.js
application/modules/admin/static/js/codemirror/addon/fold/foldgutter.js
application/modules/admin/static/js/codemirror/addon/hint/css-hint.js
application/modules/admin/static/js/codemirror/addon/hint/show-hint.css
application/modules/admin/static/js/codemirror/addon/hint/show-hint.js
application/modules/admin/static/js/codemirror/addon/selection/active-line.js
application/modules/admin/static/js/codemirror/codemirror.css
application/modules/admin/static/js/codemirror/codemirror.js
application/modules/admin/static/js/codemirror/keymap/sublime.js
application/modules/admin/static/js/codemirror/mode/css/css.js

- Update CodeMirror to 5.65.12
Seems to be working as before after the update.
There is a new major version of CodeMirror. CodeMirror 5 still seems to be under development tho.

Update CodeMirror to 5.65.12

---

application/modules/admin/config/config.php
application/modules/guestbook/config/config.php
application/modules/guestbook/controllers/Index.php
application/modules/guestbook/controllers/admin/Index.php
application/modules/guestbook/controllers/admin/Settings.php
application/modules/guestbook/mappers/Guestbook.php
application/modules/guestbook/models/Entry.php
application/modules/guestbook/views/admin/index/index.php
application/modules/guestbook/views/index/index.php
application/modules/guestbook/views/index/newentry.php

- Updates for FontAwesome 6
- Some code style fixes
- https://github.com/IlchCMS/Ilch-2.0/issues/635

Guestbook: Updates for FontAwesome 6

---

application/libraries/Ilch/Layout/Frontend.php
application/libraries/Ilch/Layout/Helper/ScriptTag/Model.php
tests/libraries/ilch/Layout/Helper/ScriptTag/ScriptTagTest.php

Adding script tags dynamically
Fixes #453

Issue453: adding script tags dynamically

---

application/modules/awards/controllers/Index.php
application/modules/awards/translations/de.php
application/modules/awards/translations/en.php
application/modules/awards/views/admin/index/index.php
application/modules/awards/views/index/index.php
application/modules/awards/views/index/show.php

- Add icons to differentiate users from teams
- Some small fixes

Add icons to differentiate users from teams

---

tests/libraries/ilch/Layout/Helper/MetaTag/MetaTagTest.php

Add some unit tests for creating meta tags.

Add some unit tests for creating meta tags.

---

application/libraries/Ilch/Layout/Frontend.php
application/libraries/Ilch/Layout/Helper/LinkTag/Model.php
tests/libraries/ilch/Layout/Helper/LinkTag/LinkTagTest.php
tests/libraries/ilch/Layout/Helper/ScriptTag/ScriptTagTest.php

- Add support for various new or previously unsupported attributes.
- Added some unit tests.
This is a breaking change. ~~Probably better to ship this only after informing developers of the upcoming changes.~~ (Adding note to release news).
- Exceptions thrown when value is invalid.
- Attributes might not be added if not allowed by spec.

Update the link tag implementation

---

application/modules/gallery/boxes/views/pictureofx.php
application/modules/gallery/config/config.php
application/modules/gallery/controllers/Index.php
application/modules/gallery/controllers/admin/Gallery.php
application/modules/gallery/controllers/admin/Image.php
application/modules/gallery/controllers/admin/Index.php
application/modules/gallery/controllers/admin/Settings.php
application/modules/gallery/models/GalleryItem.php
application/modules/gallery/models/Image.php
application/modules/gallery/static/js/custom.js
application/modules/gallery/translations/de.php
application/modules/gallery/translations/en.php
application/modules/gallery/views/admin/index/index.php
application/modules/gallery/views/index/index.php
application/modules/gallery/views/index/show.php

- Fix "Call to a member function getCat() on null"
- Further fixed a similar issue in another action and fontawesome 6 adjustments.
https://github.com/IlchCMS/Ilch-2.0/issues/635

Fix "Call to a member function getCat() on null"

---

application/modules/checkoutbasic/config/config.php
application/modules/checkoutbasic/controllers/Index.php
application/modules/checkoutbasic/controllers/admin/Currency.php
application/modules/checkoutbasic/controllers/admin/Index.php
application/modules/checkoutbasic/mappers/Checkout.php
application/modules/checkoutbasic/mappers/Currency.php
application/modules/checkoutbasic/models/Currency.php
application/modules/checkoutbasic/models/Entry.php
application/modules/checkoutbasic/translations/de.php
application/modules/checkoutbasic/translations/en.php
application/modules/checkoutbasic/views/admin/currency/index.php
application/modules/checkoutbasic/views/admin/currency/treat.php
application/modules/checkoutbasic/views/admin/index/index.php
application/modules/checkoutbasic/views/admin/index/settings.php
application/modules/checkoutbasic/views/admin/index/treatPayment.php
application/modules/checkoutbasic/views/index/index.php

Ilch-Core und PHP-Version Anpassung
FontAwesome 6 #635
Code Verbesserung

checkoutbasic - V1.5.0

---

application/modules/faq/config/config.php
application/modules/faq/controllers/Index.php
application/modules/faq/controllers/admin/Cats.php
application/modules/faq/controllers/admin/Index.php
application/modules/faq/controllers/admin/Settings.php
application/modules/faq/mappers/Category.php
application/modules/faq/mappers/Faq.php
application/modules/faq/models/Category.php
application/modules/faq/models/Faq.php
application/modules/faq/translations/de.php
application/modules/faq/translations/en.php
application/modules/faq/views/admin/cats/index.php
application/modules/faq/views/admin/cats/treat.php
application/modules/faq/views/admin/index/index.php
application/modules/faq/views/admin/index/treat.php
application/modules/faq/views/admin/settings/index.php
application/modules/faq/views/index/index.php
application/modules/faq/views/index/show.php

Ilch-Core und PHP-Version Anpassung
FontAwesome 6 #635
Rechte-Update
Code Verbesserung

faq - V1.9.0

---

application/modules/vote/boxes/Vote.php
application/modules/vote/boxes/views/vote.php
application/modules/vote/config/config.php
application/modules/vote/controllers/Index.php
application/modules/vote/controllers/admin/Index.php
application/modules/vote/mappers/Ip.php
application/modules/vote/mappers/Result.php
application/modules/vote/mappers/Vote.php
application/modules/vote/models/Ip.php
application/modules/vote/models/Result.php
application/modules/vote/models/Vote.php
application/modules/vote/translations/de.php
application/modules/vote/translations/en.php
application/modules/vote/views/admin/index/index.php
application/modules/vote/views/admin/index/treat.php
application/modules/vote/views/index/index.php

Ilch-Core und PHP-Version Anpassung
FontAwesome 6 #635
Rechte-Update
mehrfachauswahl möglichkeit Fix #548
Code Verbesserung

vote - V1.12.0

---

application/modules/faq/config/config.php

FAQ module: Fix typo

---

application/modules/forum/config/config.php
application/modules/forum/controllers/Showposts.php
application/modules/forum/controllers/admin/Index.php
application/modules/forum/controllers/admin/Ranks.php
application/modules/forum/controllers/admin/Reports.php
application/modules/forum/controllers/admin/Settings.php
application/modules/forum/mappers/Post.php
application/modules/forum/translations/de.php
application/modules/forum/translations/en.php
application/modules/forum/views/Showunansweredtopics/index.php
application/modules/forum/views/admin/index/index.php
application/modules/forum/views/admin/settings/groupappearance.php
application/modules/forum/views/index/index.php
application/modules/forum/views/newpost/index.php
application/modules/forum/views/newtopic/index.php
application/modules/forum/views/showactivetopics/index.php
application/modules/forum/views/showcat/index.php
application/modules/forum/views/shownewposts/index.php
application/modules/forum/views/showposts/index.php
application/modules/forum/views/showtopics/index.php

- Fix "Trying to access array offset on value of type null"
- Adjustments for FontAwesome 6 (#635)
Fixes #660

Fix "Trying to access array offset on value of type null"

---

application/modules/forum/views/showposts/index.php

- Forum: FontAwesome 6 adjustment

Forum: FontAwesome 6 adjustment

---

application/modules/shop/config/config.php
application/modules/shop/views/admin/items/treat.php

- Fix clear buttons not working-
- Fixed labels.

Shop: fix clear buttons not working

---

application/modules/contact/views/admin/index/treat.php

Fix wrong php short opening tag

Fix wrong php short opening tag

---

application/libraries/Ilch/Controller/Base.php
application/libraries/Ilch/Database/Mysql.php
application/modules/install/controllers/Index.php
application/modules/install/layouts/index.php
application/modules/install/translations/de.php
application/modules/install/translations/en.php
application/modules/install/views/index/ajaxconfig.php
application/modules/install/views/index/configuration.php
application/modules/install/views/index/connect.php
application/modules/install/views/index/database.php
application/modules/install/views/index/finish.php
application/modules/install/views/index/index.php
application/modules/install/views/index/license.php
application/modules/install/views/index/systemcheck.php

Install-Modul

---

static/js/ckeditor/config_ilch_html.js

Add CodeSnippet and SpecialChar to the toolbar as this was part of the config for the frontend, but somehow missing in this one.

Update config_ilch_html.js (CodeSnippet and SpecialChar)

---

application/modules/user/controllers/Panel.php
application/modules/user/mappers/Dialog.php
application/modules/user/models/Dialog.php

- avatar was created dynamically.
- Further various code improvements.

Fix "Creation of dynamic property is deprecated"

---

application/modules/forum/mappers/Post.php

Fix duplicated db queries in getPostsByTopicId by adding a cache for the results of getAllPostsByUserId.
getAllPostsByUserId() was called for every post in the topic - even if multiple posts where posted by the same user.

Fix duplicated db queries in getPostsByTopicId

---

application/modules/gallery/config/config.php
application/modules/gallery/views/index/showimage.php

Add image details (title and description) to the showimage view.
https://www.ilch.de/forum-showposts-58594.html

Add image details to showimage view

---

application/modules/forum/controllers/Showposts.php
application/modules/forum/mappers/Post.php
application/modules/forum/views/showposts/index.php

Forum: small code style fixes

---

application/modules/user/config/config.php
application/modules/user/views/panel/navi.php

Update icons in user_menu
https://github.com/IlchCMS/Ilch-2.0/issues/635

User: update icons in user_menu

---

application/libraries/Ilch/Design/Base.php
application/modules/media/static/js/ilchyoutubehtml/dialogs/ilchyoutubehtml.js

Fix ilchyoutubehtml

---

application/modules/bbcodeconvert/controllers/admin/Index.php

* Fix limits and avoid recalculation.

bbcodeconvert: fix limits and avoid recalculation

---

application/modules/bbcodeconvert/config/config.php
application/modules/bbcodeconvert/controllers/admin/Index.php
application/modules/bbcodeconvert/mappers/User.php
application/modules/bbcodeconvert/views/admin/index/convert.php

* fix wrong column name
* fix division by zero in progress bar
* update ilch core requirement

bbcodeconvert: fix wrong column name and division by zero

---

application/modules/admin/config/config.php
composer.lock

Update CKEditor to 4.22.1 and FontAwesome to 6.4.2

Update CKEditor to 4.22.1 and FontAwesome to 6.4.2

---

application/modules/bbcodeconvert/static/css/bbcodeconvert_styles.css
application/modules/bbcodeconvert/views/admin/index/index.php
application/modules/events/config/config.php
application/modules/events/controllers/Index.php
application/modules/events/controllers/admin/Index.php
application/modules/events/static/css/events.css
application/modules/events/views/events/index.php
application/modules/events/views/index/treat.php
application/modules/events/views/show/event.php
application/modules/forum/boxes/views/forum.php
application/modules/forum/controllers/Newpost.php
application/modules/forum/controllers/Shownewposts.php
application/modules/forum/mappers/Remember.php
application/modules/forum/static/css/forum.css
application/modules/forum/views/Showunansweredtopics/index.php
application/modules/forum/views/admin/index/index.php
application/modules/forum/views/edittopic/index.php
application/modules/forum/views/index/index.php
application/modules/forum/views/newtopic/index.php
application/modules/forum/views/showactivetopics/index.php
application/modules/forum/views/showcat/index.php
application/modules/forum/views/shownewposts/index.php
application/modules/forum/views/showposts/index.php
application/modules/forum/views/showtopics/index.php
application/modules/guestbook/config/config.php
application/modules/jobs/views/index/show.php

Various smaller code style fixes
- Removed no longer used show action in the index controller of the admincenter of the events module.

Various smaller code style fixes and removed dead code

---

application/libraries/Captcha/DefaultCaptcha.php
application/libraries/Captcha/GoogleCaptcha.php
application/modules/shoutbox/boxes/Shoutbox.php
application/modules/shoutbox/boxes/views/shoutbox.php
application/modules/shoutbox/config/config.php
application/modules/shoutbox/controllers/Index.php
application/modules/shoutbox/controllers/admin/Index.php
application/modules/shoutbox/controllers/admin/Settings.php
application/modules/shoutbox/mappers/Shoutbox.php
application/modules/shoutbox/models/Shoutbox.php
application/modules/shoutbox/translations/de.php
application/modules/shoutbox/translations/en.php
application/modules/shoutbox/views/admin/index/index.php
application/modules/shoutbox/views/admin/index/reset.php
application/modules/shoutbox/views/admin/settings/index.php
application/modules/shoutbox/views/index/index.php

#635
Code Verbesserungen
Captcha Einbindung
Möglichkeit DB zu leeren

Schoutbox v1.5.0

---

application/modules/bbcodeconvert/controllers/admin/Index.php
application/modules/bbcodeconvert/translations/de.php
application/modules/bbcodeconvert/translations/en.php

- Add support for kvticket and radiohoerercharts

bbcodeconvert: add support for kvticket and radiohoerercharts

---

application/modules/statistic/controllers/Index.php
application/modules/statistic/controllers/admin/Index.php
application/modules/statistic/models/Statisticconfig.php

https://www.ilch.de/forum-showposts-58604-p1.html#407487

Statistic fix

---

application/modules/forum/mappers/Forum.php
application/modules/forum/views/index/index.php

- Reduced DB queries.
- Fixed post count (always showed 0).

Forum: Reduce DB queries and fix post count

---

application/libraries/Ilch/Layout/Frontend.php

- Add needed javascript and css files of the codesnippet plugin to the frontend.

CKEditor codesnippet: Add files to frontend

---

application/modules/shoutbox/config/config.php
application/modules/shoutbox/mappers/Shoutbox.php

Shoutbox V1.5.1

---

application/modules/shop/config/config.php
application/modules/shop/controllers/Index.php
application/modules/shop/mappers/Items.php
application/modules/shop/translations/de.php
application/modules/shop/translations/en.php
application/modules/shop/views/index/index.php

Added selection to show all products regardless of category in the shop
Fixes # (issue)

Select view all products

---

application/modules/forum/controllers/Index.php
application/modules/forum/controllers/Showcat.php
application/modules/forum/controllers/Shownewposts.php
application/modules/forum/controllers/Showposts.php
application/modules/forum/controllers/Showtopics.php
application/modules/forum/mappers/Forum.php
application/modules/forum/mappers/Post.php
application/modules/forum/mappers/Topic.php
application/modules/forum/mappers/TopicSubscription.php
application/modules/forum/mappers/TrackRead.php
application/modules/forum/models/ForumPost.php
application/modules/forum/models/ForumTopic.php
application/modules/forum/views/Showunansweredtopics/index.php
application/modules/forum/views/index/index.php
application/modules/forum/views/showactivetopics/index.php
application/modules/forum/views/showcat/index.php
application/modules/forum/views/shownewposts/index.php
application/modules/forum/views/showposts/index.php
application/modules/forum/views/showtopics/index.php

- Reduce database queries
- Fix condition for marking of read topic.
- Try to update instead of doing an extra query to check if a row exists in markTopicAsRead()
- Add markForumAsRead()
- Fix "After posting a forum is considered as completely read"
Fixes #491

Forum: Bug fixes and optimisations

---

application/modules/forum/mappers/Forum.php
application/modules/shop/controllers/Index.php
application/modules/statistic/mappers/Statistic.php

- setId(): Argument must be of type int, null given
- columnWithValueExists(): Return value must be of type bool, null
- getShopItemById(): Argument must be of type int, string given

Fix a few type errors.

---

application/modules/history/config/config.php
application/modules/history/controllers/Index.php
application/modules/history/controllers/admin/Index.php
application/modules/history/controllers/admin/Settings.php
application/modules/history/mappers/History.php
application/modules/history/models/History.php
application/modules/history/static/css/history.css
application/modules/history/static/js/main.js
application/modules/history/translations/de.php
application/modules/history/translations/en.php
application/modules/history/views/admin/index/index.php
application/modules/history/views/admin/index/treat.php
application/modules/history/views/admin/settings/index.php
application/modules/history/views/index/index.php

Geschichte V1.9.0

---

application/modules/rule/config/config.php
application/modules/rule/controllers/Index.php
application/modules/rule/controllers/admin/Cats.php
application/modules/rule/controllers/admin/Index.php
application/modules/rule/controllers/admin/Settings.php
application/modules/rule/mappers/Rule.php
application/modules/rule/models/Rule.php
application/modules/rule/translations/de.php
application/modules/rule/translations/en.php
application/modules/rule/views/admin/cats/index.php
application/modules/rule/views/admin/cats/treat.php
application/modules/rule/views/admin/index/index.php
application/modules/rule/views/admin/index/treat.php
application/modules/rule/views/admin/settings/index.php
application/modules/rule/views/index/index.php

#635
Code Verbesserungen
Rechte-Update

Regeln V1.8.0

---

application/modules/forum/controllers/Showposts.php
application/modules/shop/views/index/cart.php

- Check for invalid cart
- Escape product name from shopping cart in session.
- Fix error in forum if no forum found with the topic id.

Check for invalid cart and more

---

application/modules/events/static/upload/.gitignore
application/modules/history/controllers/admin/Index.php
application/modules/history/controllers/admin/Settings.php
application/modules/user/static/upload/.gitignore

kleine änderungen

---

application/modules/bbcodeconvert/config/config.php
application/modules/bbcodeconvert/controllers/admin/Index.php

bbcodeconvert: update supported versions

---

application/modules/away/config/config.php

- Fix adding calendar_events entry
#781

away: fix adding calendar_events entry

---

application/modules/install/layouts/index.php
application/modules/install/translations/de.php
application/modules/install/translations/en.php

Install: add missing translation

---

application/modules/gallery/config/config.php
application/modules/gallery/controllers/admin/Index.php
application/modules/gallery/mappers/Gallery.php
application/modules/gallery/views/admin/index/index.php

Beim Erstellen einer Galerie wurde die Kategorie nicht gespeichert

Fehler beim erstellen einer Galerie

---

application/layouts/clan3columns/style.css
application/libraries/Ilch/Comments.php
application/libraries/Ilch/View.php
application/modules/admin/views/admin/menu/index.php
application/modules/gallery/views/admin/gallery/treatgallery.php
application/modules/gallery/views/admin/index/index.php
application/modules/gallery/views/admin/settings/index.php
application/modules/gallery/views/index/index.php
application/modules/war/views/admin/ajax/game.php
application/modules/war/views/admin/enemy/treat.php
application/modules/war/views/admin/group/treat.php
application/modules/war/views/admin/icons/treat.php
application/modules/war/views/admin/index/treat.php
application/modules/war/views/admin/maps/treat.php
application/modules/war/views/admin/settings/index.php
application/modules/war/views/group/index.php
application/modules/war/views/group/show.php
application/modules/war/views/index/index.php
application/modules/war/views/index/show.php
composer.lock

Changes from https://github.com/IlchCMS/Ilch-2.0/pull/790 by @Slipi85 
> Update Gallery Modul Front
Changed in this PR compared to the original one
- removed uploaded images
- remove accidental revert of changes to optimize-vendor
- remove readding of bootstrap from a cdn

Changes from PR 790 Update Gallery Modul Front

---

composer.json
composer.lock

**This is a harmless pull request, which needed to be done for getting some nice screenshots for a documentation.**
- Update composer.json for BS 5.3.2

Update composer.json for BS 5.3.2

---

application/modules/jobs/boxes/Jobs.php
application/modules/jobs/boxes/views/jobs.php
application/modules/jobs/config/config.php
application/modules/jobs/controllers/Index.php
application/modules/jobs/controllers/admin/Index.php
application/modules/jobs/mappers/Jobs.php
application/modules/jobs/models/Jobs.php
application/modules/jobs/translations/de.php
application/modules/jobs/translations/en.php
application/modules/jobs/views/admin/index/index.php
application/modules/jobs/views/admin/index/treat.php
application/modules/jobs/views/index/index.php
application/modules/jobs/views/index/show.php

Beim Anlegen eines neuen Job war Id = NULL (INT erwartet)
Kleine Code Verbesserungen

Job-Modul (V1.6.1): Fehler beim Anlegen eines Jobs und Verbesserungen

---

application/modules/jobs/controllers/Index.php

- Use alwaysPurify as we are dealing with non-admin user supplied input.

Jobs: Use alwaysPurify

---

application/modules/user/plugins/AfterDatabaseLoad.php
application/modules/user/plugins/BeforeControllerLoad.php

Fix errors after deleting logged in user
Fixes #815

Fix errors after deleting logged in user

---

application/modules/forum/config/config.php

- Delete possibly orphaned posts and topics

Forum: Delete possibly orphaned posts and topics

---

application/modules/forum/controllers/admin/Index.php
application/modules/forum/mappers/Forum.php
application/modules/guestbook/config/config.php
application/modules/guestbook/models/Entry.php
index.php

**Version 2.1.54**
https://github.com/IlchCMS/Ilch-2.0/wiki/Hinweise-f%C3%BCr-Entwickler
**Änderungen**
_Ilch:_
- Layout Options-Array erweitert um <span> Tag.
- Datenbank-Backup: Dateigröße anzeigen.
- Datenbank-Backup: Zufällige Zeichenkette im Dateinamen ausgeblendet.
- formatBytes-Funktion zur Functions-Klasse hinzugefügt.
- Mehrere Fehler beim Verarbeiten einer Datei, welche kein Bild ist, behoben.
- Fehler behoben, wenn ein angemeldeter Benutzer gelöscht wurde.
_Benutzer-Modul:_
- Fehler in der Chat-Funktion behoben, wenn anderer Benutzer gelöscht wurde.
_Install-Modul:_
- Fehlende Übersetzung hinzugefügt.
_Optionale Module:_
_Abwesenheits-Modul (1.6.1):_
- Einträge wurden nicht im Kalender angezeigt.
_BBCode-Konvertierung-Modul (1.0.2):_
- Unterstützung für die aktuelle Version von …

Version 2.1.54

---

application/libraries/Ilch/Layout/Frontend.php

https://www.ilch.de/index.php?forum-showposts-58631-p1#407796

Rechte-fix

---

application/modules/bbcodeconvert/config/config.php
application/modules/bbcodeconvert/controllers/admin/Index.php

- Update for new guestbook and forum

bbcodeconvert: update for new guestbook and forum

---

application/layouts/clan3columns/config/config.php
application/layouts/clan3columns/index.php
application/layouts/clan3columns/index_full.php
application/layouts/clan3columns/style.css
application/libraries/Ilch/Comments.php
application/modules/admin/static/css/admin.css
application/modules/admin/views/admin/boxes/index.php
application/modules/admin/views/admin/emails/index.php
application/modules/admin/views/admin/layouts/advSettings.php
application/modules/admin/views/admin/layouts/index.php
application/modules/admin/views/admin/layouts/show.php
application/modules/admin/views/admin/menu/index.php
application/modules/admin/views/admin/modules/index.php
application/modules/admin/views/admin/modules/notinstalled.php
application/modules/admin/views/admin/page/index.php
application/modules/admin/views/admin/page/treat.php
application/modules/birthday/views/index/index.php
application/modules/downloads/views/index/index.php
application/modules/forum/views/rememberedposts/index.php
application/modules/forum/views/showposts/index.php
application/modules/gallery/views/index/show.php
application/modules/guestbook/views/index/index.php
application/modules/media/views/admin/iframe/index.php
application/modules/media/views/admin/iframe/indexckeditor.php
application/modules/media/views/admin/iframe/multi.php
application/modules/newsletter/views/index/index.php
application/modules/user/views/panel/avatar.php
application/modules/user/views/panel/navi.php
application/modules/user/views/panel/signature.php
static/css/ilch.css

Fixed PS3 class to PS5 class
unter user/panel/profile lässt sich bei geburtstag der Kalender nicht öffnen.

Fixed PS3 class to PS5 class | clan3columns Layout and other views/php

---

application/layouts/clan3columns/style.css
application/libraries/Ilch/View.php
application/modules/admin/boxes/views/langswitch.php
application/modules/admin/static/css/admin.css
application/modules/admin/static/css/login.css
application/modules/admin/views/admin/index/index.php
application/modules/admin/views/admin/layouts/show.php
application/modules/article/boxes/views/categories.php
application/modules/checkoutbasic/views/admin/index/settings.php
application/modules/events/views/index/treat.php
application/modules/install/static/css/install.css
application/modules/partner/views/admin/index/index.php
application/modules/rule/views/index/index.php
application/modules/shop/static/css/style_front.css
application/modules/user/views/admin/group/access.php
application/modules/user/views/admin/index/index.php
application/modules/user/views/admin/profilefields/index.php
application/modules/user/views/admin/profilefields/treat.php
application/modules/user/views/login/index.php
application/modules/vote/views/admin/index/treat.php
static/css/ilch.css

Habe alle Punkte von Lord|Schirmer bearbeitet
https://www.ilch.de/forum-showposts-58597-p5.html#407908 
https://www.ilch.de/forum-showposts-58597-p4.html#407902
Hier eine Info zu nicht behobenen Punkt:
https://www.ilch.de/forum-showposts-58597-p5.html#407913
Werde die Tage alle selecdet ansehen und die Klasse "form-select" hinzufügen, da die das Dropdown sympol ausgibt.
btw, das Capcha wird bei mir durch das lokale aufrufen 127.0.0.1 NICHT angezeigt.

Fixed from Lord|Schirmer Test

---

application/modules/rule/config/config.php
application/modules/rule/mappers/Rule.php
application/modules/rule/models/Rule.php

https://www.ilch.de/forum-showposts-58641.html - > Positionen falsch

Rule 1.8.1 - Positionen falsch

---

application/modules/teams/config/config.php
application/modules/teams/controllers/admin/Index.php
application/modules/teams/static/upload/.gitignore

https://www.ilch.de/forum-showposts-58641.html - > Fehler beim Bild hochladen

Teams 1.23.1 - Fehler beim Bild hochladen

---

composer.lock

- Update HTMLPurifier and CKEditor
-- HTMLPurifier 4.17
-- CKEditor 4.23

Update HTMLPurifier and CKEditor

---

application/libraries/Ilch/Design/Base.php

- Fix AllowedSchemes. The previous change actually disallowed various other schemes.
Previous PR: https://github.com/IlchCMS/Ilch-2.0/pull/871

HtmlPurifier: Fixed AllowedSchemes

---

application/modules/forum/views/Showunansweredtopics/index.php
application/modules/forum/views/admin/reports/index.php
application/modules/forum/views/admin/reports/show.php
application/modules/forum/views/index/index.php
application/modules/forum/views/rememberedposts/index.php
application/modules/forum/views/showactivetopics/index.php
application/modules/forum/views/showcat/index.php
application/modules/forum/views/shownewposts/index.php
application/modules/forum/views/showtopics/index.php

- Show date and time in local timezone
- Fix missing underline for "mark all as read"
- Small code style changes
Fixes #864

Forum: show date and time in local timezone

---

application/modules/link/config/config.php
application/modules/link/controllers/Index.php
application/modules/link/controllers/admin/Index.php
application/modules/link/mappers/Category.php
application/modules/link/mappers/Link.php
application/modules/link/models/Category.php
application/modules/link/models/Link.php
application/modules/link/translations/de.php
application/modules/link/translations/en.php
application/modules/link/views/admin/index/index.php
application/modules/link/views/admin/index/treatCat.php
application/modules/link/views/admin/index/treatLink.php
application/modules/link/views/index/index.php

PSR korrigiert
Desc wird nun auch verlinkt

Link 1.10.1 - kleines Update

---

application/modules/admin/config/config.php

Update vendor directory for the update of ckeditor and htmlpurifier.

Update vendor directory

---

application/modules/downloads/config/config.php
application/modules/downloads/mappers/File.php
application/modules/downloads/views/index/showfile.php

- Fixed "argument must be of type string, null given"
https://www.ilch.de/forum-showposts-58642.html

Downloads: Fixed "argument must be of type string, null given"

---

composer.lock

PHPMailer 6.9.1

---

.github/workflows/ci.yaml

- Add PHP 8.3 to the CI workflow
https://www.php.net/archive/2023.php#2023-11-23-2

Add PHP 8.3 to the CI workflow

---

application/modules/admin/config/config.php
application/modules/bbcodeconvert/config/config.php
application/modules/bbcodeconvert/controllers/admin/Index.php
composer.json
composer.lock
index.php

CKEditor 4.23 is an LTS version, which requires a license.
https://www.ilch.de/forum-showposts-58648.html

Downgrade CKEditor to 4.22.1

---

application/modules/faq/config/config.php
application/modules/faq/controllers/admin/Cats.php
application/modules/faq/views/admin/index/treat.php
application/modules/faq/views/index/index.php

- Fehler behoben -> "count(): Argument #1 ($value) must be of type Countable|array, null given"
- Gruppen wurden nicht richtig dargestellt

FAQ - Fehler behoben

---

application/libraries/Ilch/Layout/Helper/Title/Model.php
index.php

**Version 2.1.57**
<a href="https://github.com/IlchCMS/Ilch-2.0/wiki/Hinweise-f%C3%BCr-Entwickler" target="_blank">Hinweise für Entwickler</a>  
**Ilch:**  
- Fehler bei fehlender Lokalisierung einer Box behoben.  
- Dynamische Einstellung für den Titel.
**BBCode-Konvertierung-Modul (1.0.5):**
- Unterstützung für die aktuelle Version von Ilch und dem Forum-Modul.
**Kalender-Modul (1.10.0):**
- FullCalendar auf Version 6.1.10 aktualisiert.  
- Schaltfläche für eine Monatliche Jahresansicht hinzugefügt.
**F.A.Q.-Modul (1.9.2):**
- Fehler bei der Deinstallation behoben.  
- Gruppen wurden nicht richtig dargestellt.  
- Fehler bei leeren Kategorien behoben.
**Forum-Modul (1.34.5):**
- Gelesene Themen wurden in einigen Fällen fälschlicherweise als ungelesen angezeigt.  
- Präfix-Funktion …

Version 2.1.57

---

application/modules/admin/controllers/admin/Index.php
application/modules/admin/layouts/index.php
application/modules/admin/views/admin/index/index.php

Fehler bei Anzeige im Backend behoben

Fehler bei Anzeige im Backend behoben

---

application/modules/training/boxes/Nexttraining.php
application/modules/training/boxes/views/nexttraining.php
application/modules/training/config/config.php
application/modules/training/controllers/Index.php
application/modules/training/controllers/Trainings.php
application/modules/training/controllers/admin/Index.php
application/modules/training/controllers/admin/Settings.php
application/modules/training/mappers/Entrants.php
application/modules/training/mappers/Training.php
application/modules/training/models/Entrants.php
application/modules/training/models/Training.php
application/modules/training/translations/de.php
application/modules/training/translations/en.php
application/modules/training/views/admin/index/index.php
application/modules/training/views/admin/index/treat.php
application/modules/training/views/admin/settings/index.php
application/modules/training/views/index/index.php
application/modules/training/views/index/show.php
application/modules/training/views/trainings/index.php
tests/modules/training/_files/mysql_database.yml
tests/modules/training/mappers/EntrantsTest.php
tests/modules/training/mappers/TrainingTest.php

Test's erstellt
Rechte Update
FA Update (#635)
PSR fix

Taining V1.8.0 - Update

---

application/modules/install/controllers/Index.php
application/modules/install/translations/de.php
application/modules/install/translations/en.php

Installations Fehler abfangen

---

application/libraries/Ilch/Layout/Helper/Menu/Model.php

- Add missing change that should have landed as part of an earlier PR.
https://github.com/IlchCMS/Ilch-2.0/issues/891

Issue 891: Add missing change

---

application/modules/events/config/config.php
application/modules/events/views/show/event.php

- Show comments below event details
Fixes #909

Events: Show comments below event details

---

application/modules/admin/layouts/index.php
application/modules/admin/layouts/maintenance.php
application/modules/article/views/archive/show.php
application/modules/article/views/cats/show.php
application/modules/article/views/index/index.php
application/modules/article/views/keywords/show.php
application/modules/away/views/index/index.php
application/modules/downloads/views/index/showfile.php
application/modules/shop/views/payment/index.php
application/modules/statistic/views/index/show.php
application/modules/user/views/iframe/multi.php
composer.lock

Die Klasse Pull-left und pull-right wurden unbenannt zu float-start und float-end.
Da ich mit der Suchfunktion gearbeitet habe, müßten alle pull klassen bearbeitet sein.

Update class pull to float

---

application/modules/downloads/views/index/index.php
application/modules/gallery/static/css/gallery.css
application/modules/jobs/views/index/show.php
application/modules/statistic/views/index/index.php
application/modules/user/static/css/user.css
application/modules/user/views/gallery/index.php

- Replace text-left with text-start
https://getbootstrap.com/docs/5.2/migration/#utilities
https://www.ilch.de/forum-showposts-58597-p5.html#408090

BS5: Replace text-left with text-start

---

application/modules/article/views/admin/index/index.php
application/modules/media/views/admin/ajax/index.php
application/modules/media/views/admin/ajax/multi.php
application/modules/media/views/admin/iframe/indexckeditor.php
application/modules/media/views/admin/iframe/multi.php
application/modules/shop/views/admin/items/index.php
application/modules/shop/views/admin/items/treat.php
application/modules/shop/views/admin/orders/treat.php
application/modules/shop/views/admin/settings/default.php
application/modules/shop/views/customerarea/show.php
application/modules/shop/views/index/order.php
application/modules/shop/views/payment/index.php
application/modules/training/boxes/views/nexttraining.php
application/modules/war/boxes/views/lastwar.php
application/modules/war/boxes/views/nextwar.php

- Replace text-right with text-end
https://getbootstrap.com/docs/5.2/migration/#utilities
https://www.ilch.de/forum-showposts-58597-p5.html#408090

BS5: Replace text-right with text-end

---

application/libraries/Ilch/Comments.php
application/libraries/Ilch/View.php
application/modules/downloads/views/admin/downloads/treatdownloads.php
application/modules/gallery/views/admin/gallery/treatgallery.php
application/modules/media/views/admin/ajax/index.php
application/modules/media/views/admin/ajax/multi.php
application/modules/media/views/admin/iframe/index.php
application/modules/partner/boxes/views/partner.php
application/modules/user/views/admin/index/treat.php
application/modules/user/views/admin/providers/edit.php
application/modules/user/views/iframe/multi.php
application/modules/user/views/panel/dialog.php
application/modules/user/views/panel/navi.php
application/modules/war/views/group/show.php
static/js/validate/ilch-validate.js

- Replaced form-control-static with form-control-plaintext
- Replaced help-block with form-text
- Replaced .img-circle to .rounded-circle
- Replaced .img-responsive with .img-fluid

BS5: Various fixes

---

tests/libraries/ilch/Design/BasePurifyTest.php

CKEditor 5: Add a few unit tests

---

application/modules/admin/controllers/admin/Layouts.php
application/modules/admin/mappers/LayoutAdvSettings.php
application/modules/admin/models/LayoutAdvSettings.php
application/modules/admin/views/admin/layouts/advSettings.php
application/modules/admin/views/admin/layouts/advSettingsShow.php

- "textarea" hinzugefügt
- "text" Länge geändert
- Code Verbesserung

Erweiterte-Layout-Einstellung

---

application/libraries/Ilch/Design/Base.php
tests/libraries/ilch/Design/BasePurifyTest.php

- Added unit tests for embedding a local hosted video with the ilchmedia plugin.
- Adjusted HTMLPurifier configuration.

CKEditor 5: Added two unit tests and adjusted HTMLPurifier config

---

application/libraries/Ilch/Design/Base.php
static/js/ilch.js
tests/libraries/ilch/Design/BasePurifyTest.php

- Fix missing protocol by adjusting the CKEditor 5 configuration
- Adjusted the unit tests and HTMLPurifier configuration to this.

Ckeditor5: Fixed missing protocol

---

application/libraries/Ilch/Translations/de.php
application/libraries/Ilch/Translations/en.php
application/modules/article/views/admin/index/treat.php
application/modules/article/views/admin/templates/treat.php
application/modules/forum/views/showposts/index.php
application/modules/user/views/admin/settings/index.php

- Add some missing changes to the forum from master.
- Added translation for "noMedias" globally.
- Remove reference to old ilchPsPlugin.

Bootstrap5, CKEditor5: Add some missing changes

---

application/modules/shop/controllers/Index.php
application/modules/shop/translations/de.php
application/modules/shop/translations/en.php
application/modules/shop/views/index/order.php

- Add link to register and forgot password
https://www.ilch.de/forum-showposts-58689-p1.html#408189

Shop: Add link to register and forgot password

---

application/modules/shop/controllers/Index.php

- Check for missing itemDetails. Likely caused by deleted product.
https://www.ilch.de/forum-showposts-58689-p1.html#408188

Shop: Check for missing itemDetails

---

application/modules/user/static/css/message.css
application/modules/user/views/panel/dialog.php

- Fix CKEditor and other parts of the right dialog column not fitting inside parent div and being cut off. Therefore it was impossible to use it and send a message.
This was the case for a few layouts and not a general problem.
https://www.ilch.de/forum-showposts-58697.html

User: Fix user dialog being cut off and impossible to use

---

application/modules/war/config/config.php
application/modules/war/views/admin/index/index.php

War: Fix filter

---

application/modules/gallery/boxes/Pictureofx.php
application/modules/gallery/config/config.php
application/modules/gallery/controllers/admin/Index.php

- Fix errors with missing gallery and missing gallery box settings
https://www.ilch.de/forum-showposts-58703.html

Gallery: Fix errors with missing gallery and missing gallery settings

---

application/modules/bbcodeconvert/config/config.php
application/modules/bbcodeconvert/controllers/admin/Index.php

bbcodeconvert: update for ilch 2.1.60

---

application/modules/admin/config/config.php

- Just adding the case for Ilch 2.1.59 before adding further cases in the Bootstrap5-CKEditor5 branch.

Update admin config.php

---

.github/workflows/build.yaml

Build script: Add quiet -q option

---

application/modules/guestbook/views/admin/settings/index.php

- Remove remnants of merge error and required attribute.
It was impossible to save the settings and and error appeared when selecting the ckeditor.

Guestbook: Remove remnants of merge error and required

---

.github/workflows/build.yaml
build/optimize_build.php

Remove code for removal of the handpicked files. Replace this part of optimize_build.php with a one liner in the build.yaml.

Build scripts: Remove code for removal of the handpicked files

---

static/js/ilch.js

Update ilch.js: More flexible image toolbar
https://www.ilch.de/forum-showposts-58708-p1.html#408393
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageconfig-ImageConfig.html#member-toolbar

Update ilch.js: More flexible image toolbar

---

application/modules/admin/views/admin/layouts/index.php

Hier wurde nur die lokale IlchCore Version überprüft

ilchCore überprüfung bei Updateserver

---

application/modules/admin/views/admin/modules/search.php

Fix errors in search view of module update
https://www.ilch.de/forum-showposts-58717.html

Fix errors in search view of module update

---

application/libraries/Ilch/Functions.php
application/libraries/Thumb/Thumbnail.php
application/modules/admin/views/admin/infos/logs.php

#917 zum größten teils geändert
PSR fix
BS5 fix

Php8 support

---

application/modules/admin/controllers/admin/Layouts.php

- Small bugfix for the breadcrumb option

Small bugfix for the breadcrumb option

---

application/modules/admin/views/admin/layouts/show.php
application/modules/admin/views/admin/modules/show.php

Remove vote leftover from earlier PR

Remove vote leftover from earlier PR

---

application/modules/admin/views/admin/emails/index.php
application/modules/admin/views/admin/index/index.php
application/modules/admin/views/admin/infos/allrights.php
application/modules/admin/views/admin/infos/certificate.php
application/modules/admin/views/admin/infos/folderrights.php
application/modules/admin/views/admin/infos/logs.php
application/modules/admin/views/admin/layouts/advSettings.php
application/modules/admin/views/admin/layouts/index.php
application/modules/admin/views/admin/layouts/search.php
application/modules/admin/views/admin/layouts/show.php
application/modules/admin/views/admin/menu/index.php
application/modules/admin/views/admin/modules/index.php
application/modules/admin/views/admin/modules/notinstalled.php
application/modules/admin/views/admin/modules/search.php
application/modules/admin/views/admin/modules/show.php
application/modules/admin/views/admin/modules/updates.php
application/modules/admin/views/admin/page/index.php
application/modules/admin/views/admin/settings/index.php
application/modules/admin/views/admin/settings/maintenance.php
application/modules/admin/views/admin/settings/notifications.php
application/modules/admin/views/admin/settings/update.php

- Some codestyle fixes
- Missing table row elements
- Missing id needed by a label
- Replaced div by label
- Fix class small not applied to everything

Some codestyle fixes and other smaller fixes

---

application/modules/user/static/css/user.css
application/modules/user/views/admin/index/index.php

- Add sorting and filtering of the user table in the admincenter.
Fixes #429

Admincenter: Sorting and filtering of user table

---

application/modules/shop/config/config.php
application/modules/shop/static/css/shop_admin.css
application/modules/shop/views/admin/items/index.php

Use same filtering as in admin and user

Shop: Use same filtering as in admin and user

---

application/modules/shop/static/css/style_front.css

Shop: Remove no longer needed CSS

---

application/modules/admin/config/config.php

- Add second updateserver.
- Evenly distribute chosen updateserver.
- Fix updateserver information.

Add second updateserver

---

application/modules/gallery/config/config.php
application/modules/gallery/views/index/show.php

Bilder wurden untereinander angezeigt: https://www.ilch.de/index.php?forum-showposts-58728-p1#408546

Galerie - V1.23.1

---

application/libraries/Ilch/Functions.php
application/modules/admin/controllers/admin/Index.php
application/modules/admin/controllers/admin/Settings.php
application/modules/admin/views/admin/index/index.php

- Reduce connection timeout in url_get_contents.
- Load news only if the updateserver is responding.
- Fixed typo.

Reduce connection timeout and load news if the updateserver is responding.

---

application/modules/admin/boxes/Layoutswitch.php
application/modules/admin/controllers/admin/Backup.php
application/modules/admin/controllers/admin/Infos.php
application/modules/admin/controllers/admin/Modules.php
application/modules/admin/controllers/admin/Settings.php
application/modules/admin/layouts/maintenance.php
application/modules/admin/mappers/Module.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/layouts/index.php
application/modules/admin/views/admin/layouts/search.php
application/modules/admin/views/admin/modules/index.php
application/modules/admin/views/admin/modules/notinstalled.php
application/modules/admin/views/admin/modules/search.php
application/modules/admin/views/admin/modules/updates.php
application/modules/admin/views/admin/settings/index.php
application/modules/admin/views/admin/settings/update.php

- Small code style improvements
- Rename "Ilch 2 UPDATE PROCESS" to "Ilch 2 Update".

Small code style improvements

---

application/modules/admin/config/config.php
composer.lock

- Update FontAwesome to version 6.6.0

Update FontAwesome to version 6.6.0

---

application/modules/media/config/config.php
application/modules/media/controllers/admin/Ajax.php
application/modules/media/controllers/admin/Cats.php
application/modules/media/controllers/admin/Iframe.php
application/modules/media/controllers/admin/Import.php
application/modules/media/controllers/admin/Index.php
application/modules/media/controllers/admin/Settings.php
application/modules/media/mappers/Media.php
application/modules/media/models/Media.php
application/modules/media/static/upload/.gitignore
application/modules/media/translations/de.php
application/modules/media/translations/en.php
application/modules/media/views/admin/ajax/multi.php
application/modules/media/views/admin/iframe/index.php
application/modules/media/views/admin/iframe/indexckeditor.php
application/modules/media/views/admin/iframe/multi.php
application/modules/media/views/admin/iframe/multickeditor.php
application/modules/media/views/admin/import/index.php
application/modules/media/views/admin/index/index.php
application/modules/media/views/admin/settings/index.php

https://www.ilch.de/index.php?forum-showposts-58733-p1#408569

Media-Modul : PSR und kleiner fix

---

application/modules/admin/controllers/admin/Settings.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/settings/update.php

- Use tokens for doSave, doUpdate and clearCache.
- Code improvements.
Should be independent from #1020 , but not tested and probably best to merge both.

ilch update: use tokens

---

application/modules/admin/controllers/admin/Settings.php
application/modules/admin/views/admin/layouts/index.php
application/modules/admin/views/admin/layouts/search.php
application/modules/admin/views/admin/layouts/show.php
application/modules/admin/views/admin/modules/index.php
application/modules/admin/views/admin/modules/notinstalled.php
application/modules/admin/views/admin/modules/search.php
application/modules/admin/views/admin/modules/show.php
application/modules/admin/views/admin/modules/updates.php
development/README.md

- alt attribute not allowed for anchor element.
- Set curlErrorOccurred for update view.

Various smaller fixes

---

application/modules/guestbook/config/config.php
application/modules/guestbook/controllers/Index.php
application/modules/guestbook/controllers/admin/Index.php
application/modules/guestbook/controllers/admin/Settings.php
application/modules/guestbook/mappers/Guestbook.php
application/modules/guestbook/models/Entry.php
application/modules/guestbook/translations/de.php
application/modules/guestbook/translations/en.php
application/modules/guestbook/views/admin/index/index.php
application/modules/guestbook/views/admin/index/reset.php
application/modules/guestbook/views/admin/settings/index.php
application/modules/guestbook/views/index/index.php
application/modules/guestbook/views/index/newentry.php

Gästebuch-Modul (1.14.1): PSR-Fix

---

application/modules/calendar/boxes/Calendar.php
application/modules/calendar/boxes/views/calendar.php
application/modules/calendar/config/config.php
application/modules/calendar/controllers/Events.php
application/modules/calendar/controllers/Index.php
application/modules/calendar/controllers/admin/Index.php
application/modules/calendar/layouts/events.php
application/modules/calendar/layouts/iCal.php
application/modules/calendar/mappers/Calendar.php
application/modules/calendar/mappers/Events.php
application/modules/calendar/models/Calendar.php
application/modules/calendar/models/Events.php
application/modules/calendar/translations/de.php
application/modules/calendar/translations/en.php
application/modules/calendar/views/admin/index/index.php
application/modules/calendar/views/admin/index/treat.php
application/modules/calendar/views/events/iCal.php
application/modules/calendar/views/events/index.php
application/modules/calendar/views/events/show.php
application/modules/calendar/views/index/index.php

Kalender-Modul (1.11.1): PSR-Fix

---

application/modules/forum/boxes/views/forum.php
application/modules/forum/views/Showunansweredtopics/index.php
application/modules/forum/views/admin/index/index.php
application/modules/forum/views/admin/prefixes/treat.php
application/modules/forum/views/admin/ranks/treat.php
application/modules/forum/views/edittopic/index.php
application/modules/forum/views/index/index.php
application/modules/forum/views/newtopic/index.php
application/modules/forum/views/rememberedposts/index.php
application/modules/forum/views/rememberedposts/treat.php
application/modules/forum/views/showactivetopics/index.php
application/modules/forum/views/showcat/index.php
application/modules/forum/views/shownewposts/index.php
application/modules/forum/views/showposts/index.php
application/modules/forum/views/showtopics/index.php

Forum-Modul (1.35.1): Variablen beschreibungen

---

application/modules/downloads/config/config.php
application/modules/downloads/controllers/Index.php
application/modules/downloads/controllers/admin/Downloads.php
application/modules/downloads/controllers/admin/File.php
application/modules/downloads/controllers/admin/Index.php
application/modules/downloads/controllers/admin/Settings.php
application/modules/downloads/mappers/Downloads.php
application/modules/downloads/mappers/File.php
application/modules/downloads/models/DownloadsItem.php
application/modules/downloads/models/File.php
application/modules/downloads/translations/de.php
application/modules/downloads/translations/en.php
application/modules/downloads/views/admin/downloads/treatdownloads.php
application/modules/downloads/views/admin/file/treatfile.php
application/modules/downloads/views/admin/index/index.php
application/modules/downloads/views/admin/settings/index.php
application/modules/downloads/views/index/index.php
application/modules/downloads/views/index/show.php
application/modules/downloads/views/index/showfile.php

Downloads-Modul (1.14.1): PSR-fix

---

application/modules/events/boxes/Events.php
application/modules/events/boxes/views/events.php
application/modules/events/config/config.php
application/modules/events/controllers/Events.php
application/modules/events/controllers/Index.php
application/modules/events/controllers/Show.php
application/modules/events/controllers/admin/Currency.php
application/modules/events/controllers/admin/Index.php
application/modules/events/controllers/admin/Settings.php
application/modules/events/mappers/Currency.php
application/modules/events/mappers/Entrants.php
application/modules/events/mappers/Events.php
application/modules/events/models/Currency.php
application/modules/events/models/Entrants.php
application/modules/events/models/Events.php
application/modules/events/translations/de.php
application/modules/events/translations/en.php
application/modules/events/views/admin/currency/index.php
application/modules/events/views/admin/currency/treat.php
application/modules/events/views/admin/index/index.php
application/modules/events/views/admin/settings/index.php
application/modules/events/views/events/index.php
application/modules/events/views/index/index.php
application/modules/events/views/index/navi.php
application/modules/events/views/index/treat.php
application/modules/events/views/show/current.php
application/modules/events/views/show/event.php
application/modules/events/views/show/participation.php
application/modules/events/views/show/past.php
application/modules/events/views/show/upcoming.php

Veranstaltungen-Modul (1.23.1): PSR fix

---

application/modules/admin/views/admin/index/index.php
application/modules/admin/views/admin/settings/update.php

- Escape version numbers from updateserver.

Escape version numbers from updateserver

---

application/modules/admin/controllers/admin/Settings.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/settings/update.php

- Update installed version in the view after an update to properly show the current installed version.
- Add button to check for further updates if there is at least one.
- Fix error if update log is empty.

Ilch Update: Update view after update

---

application/modules/user/config/config.php
application/modules/user/controllers/admin/Profilefields.php
application/modules/user/views/admin/profilefields/treat.php

User Update

---

application/modules/vote/boxes/Vote.php
application/modules/vote/boxes/views/vote.php
application/modules/vote/config/config.php
application/modules/vote/controllers/Index.php
application/modules/vote/controllers/admin/Index.php
application/modules/vote/mappers/Ip.php
application/modules/vote/mappers/Result.php
application/modules/vote/mappers/Vote.php
application/modules/vote/models/Ip.php
application/modules/vote/models/Result.php
application/modules/vote/models/Vote.php
application/modules/vote/translations/de.php
application/modules/vote/translations/en.php
application/modules/vote/views/admin/index/index.php
application/modules/vote/views/admin/index/treat.php
application/modules/vote/views/index/index.php

PSR Fix
Code Fix
Einrückung korrigiert -> daher leider etwas unübersichtlich die änderung
Fixes #955 teil 1

Umfrage V1.14.0

---

composer.lock
development/composer.lock

Update various dependencies like PHP Debug Bar.
With version 1.22.4 of the PHP Debug Bar they moved to FontAwesome 6.6, which we use for some time now.

Update various dependencies

---

application/modules/training/config/config.php
application/modules/training/mappers/Entrants.php
application/modules/training/mappers/Training.php
application/modules/training/models/Entrants.php
application/modules/training/models/Training.php
application/modules/training/translations/de.php
application/modules/training/translations/en.php

Fehlender Kalendereintrag behoben

Training-V1.9.1

---

application/modules/user/views/admin/profilefields/treat.php

- Fix "undefined index" in profilefields

User: Fix "undefined index" in profilefields

---

application/modules/user/views/panel/profile.php

- Added missing label associations

User panel, profilefields: Add missing label associations

---

application/modules/admin/config/config.php
application/modules/user/controllers/admin/Group.php
application/modules/user/controllers/admin/Profilefields.php
application/modules/user/controllers/admin/Providers.php
application/modules/user/controllers/admin/Settings.php
index.php

**Version 2.2.4**  
**Dieses Update beinhaltet Sicherheitsverbesserungen. Ein Update wird empfohlen.**  
Mit CKEditor 5 43.1.1 wurde eine Cross-Site Scripting (XSS)-Sicherheitslücke geschlossen.  
Wir ersetzen mit dieser Version Bootstrap Tokenfield und Chosen durch Choices. Die nun ersetzten Komponenten wurden schon seit längerer Zeit nicht mehr weiterentwickelt. Choices dagegen wird aktiv gepflegt. Sollten Sie in ihren eigenen Modulen Bootstrap Tokenfield oder Chosen nutzen, wird empfohlen auf Choices zu wechseln, da sie nach einer Übergangsfrist aus Ilch entfernt werden.  
Eine neue Konfigurationsmoglichkeit für die Domain wurde in die Installation von Ilch und auch in den Einstellungen von Admincenter eingefügt. Wenn Sie hier ihre öffentliche Domain eintragen, wird diese automatisch …

Beta V2.2.4

---

application/modules/admin/config/config.php
composer.lock

- Update PHPMailer to version 6.9.2

Update PHPMailer to version 6.9.2

---

composer.lock
development/composer.lock

- Update jQuery UI to version 1.14.1
- Update everything else as well.

Update jQuery UI to version 1.14.1

---

application/modules/admin/plugins/BeforeControllerLoad.php
application/modules/user/plugins/AfterDatabaseLoad.php
application/modules/user/plugins/BeforeControllerLoad.php

- Fix argument null instead of int for getUserById

Fix argument null instead of int for getUserById

---

application/modules/user/views/index/index.php
application/modules/user/views/profil/index.php

- Follow-up to fix  "empty needle"
#509

Issue 509: Follow-up to fix  "empty needle"

---

application/libraries/Ilch/Page.php

- Remove if-else - initializeHtmlPurifier
https://github.com/IlchCMS/Ilch-2.0/pull/1091

Remove if-else - initializeHtmlPurifier

---

application/modules/admin/controllers/admin/Emails.php
application/modules/admin/translations/de.php
application/modules/admin/translations/en.php
application/modules/admin/views/admin/emails/index.php
application/modules/admin/views/admin/emails/treat.php

- Handle missing email template and module.
- Add missing alt attribute for img.

Admin module: Handle missing email template and module

---

application/modules/user/controllers/admin/Group.php
application/modules/user/controllers/admin/Index.php
application/modules/user/translations/de.php
application/modules/user/translations/en.php
application/modules/user/views/admin/group/treat.php

- Fix "Group::setId(): Argument must be of type int, string given"
- Use validator for opt_gallery, admin_comments and locked.
```
PHP Fatal error:  Uncaught TypeError: Modules\User\Models\Group::setId(): Argument #1 ($id) must be of type int, string given, called in application/modules/user/models/Group.php on line 36 and defined in application/modules/user/models/Group.php:61
Stack trace:
#0 application/modules/user/models/Group.php(36): Modules\User\Models\Group->setId()
#1 application/modules/user/mappers/Group.php(119): Modules\User\Models\Group->setByArray()
#2 application/modules/user/controllers/admin/Group.php(172): Modules\User\Mappers\Group->loadFromArray()
#3 application/libraries/Ilch/Page.php(243): Modules\User\Controllers\Admin\Group->saveAction()
#4 …
```

User module: Fix various errors

---

application/modules/article/controllers/admin/Index.php
application/modules/article/translations/de.php
application/modules/article/translations/en.php

- Improve bugfix from previous PR.
#1112

Article module: Improve bugfix from previous PR

---

application/modules/user/controllers/Mail.php

- Check if recipient (user) for mail exists
```
PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in application/modules/user/controllers/Mail.php:21
Stack trace:
#0 application/libraries/Ilch/Page.php(243): Modules\User\Controllers\Mail->indexAction()
#1 application/libraries/Ilch/Page.php(137): Ilch\Page->loadController()
#2 index.php(68): Ilch\Page->loadPage()
#3 {main}
thrown in application/modules/user/controllers/Mail.php on line 21, referer: index.php/user/profil/index/user/1
```

User module: check if recipient (user) for mail exists

---

application/modules/shoutbox/boxes/Shoutbox.php
application/modules/shoutbox/config/config.php

- Fix error with userId null
https://www.ilch.de/forum-showposts-58766.html

Shoutbox: Fix error with userId null

---

application/modules/admin/mappers/Module.php

- Small changes to the module mapper

Small changes to the module mapper

---

application/libraries/Ilch/Layout/Frontend.php

- Fix error setting the language

tarteaucitron: Fix error setting the language

---

.github/workflows/ci.yaml
application/modules/admin/layouts/index.php

- Update CI workflow.
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/

Update CI workflow

---

application/modules/admin/config/config.php
composer.lock
development/composer.lock

- Update FontAwesome (v6.7.2) and several other dependencies.

Update FontAwesome and several other dependencies

---

application/libraries/Ilch/Config/Install.php
application/libraries/Ilch/Mapper.php
application/modules/install/controllers/Index.php

getConfig eingepflegt (wird immer in Modulen verwendet)
Comment-Modul beim Installieren fehlte User 1

getConfig und Fehler behoben

---

application/modules/training/config/config.php

- Revert version number change. This was already done in a previous commit.

Training: Revert version number change

---

application/modules/user/controllers/admin/Group.php

- Fix error adding new user group.
https://www.ilch.de/forum-showposts-58784.html

User: Fix error adding new user group.

---

application/modules/training/boxes/Nexttraining.php
application/modules/training/boxes/views/nexttraining.php
application/modules/training/controllers/Index.php
application/modules/training/mappers/Training.php
application/modules/training/static/css/style.css
application/modules/training/views/index/index.php

- Update the box to handle recurrent trainings.
- Update index and show view to handle recurrent trainings.

Training: Update the box and a view to handle recurrent trainings

---

index.php

**Version 2.2.7**  
Mit Version 2.2.2 wurde ein neues Zertifikat verteilt. Das alte Zertifikat läuft am 31.01.2025 ab. Aktualisieren Sie bis dahin auf Version 2.2.2 oder neuer, um weiterhin Aktualisierungen installieren zu können.  
Wir ersetzten mit Ilch 2.2.4 Bootstrap Tokenfield und Chosen durch Choices. Die ersetzten Komponenten wurden schon seit längerer Zeit nicht mehr weiterentwickelt. Choices dagegen wird aktiv gepflegt. Sollten Sie in ihren eigenen Modulen Bootstrap Tokenfield oder Chosen nutzen, wird empfohlen auf Choices zu wechseln, da sie nach einer Übergangsfrist aus Ilch entfernt werden.  
**Änderungen**  
<u>Ilch:</u>  
- Fehler beim Versuch ein Systemmodul zu deinstallieren. Systemmodule können nicht deinstalliert werden.  
- Der Cookie-Dialog wurde möglicherweise in der …

Betatest 2.2.7

---

application/modules/admin/views/admin/modules/show.php

- Fix carousel in module show view.

Admin: Fix carousel in module show view

---

application/libraries/Ilch/Transfer.php
application/modules/admin/mappers/Infos.php
application/modules/admin/mappers/Module.php
application/modules/admin/views/admin/modules/notinstalled.php
application/modules/admin/views/admin/modules/show.php
index.php

**Version 2.2.8**  
**Änderungen**  
<u>Ilch:</u>  
- Nach dem Update auf Version 2.2.7 war es nicht mehr möglich die Layout- und Sprachauswahl-Box zum Menü hinzuzufügen.  
- Nach dem Update auf Version 2.2.7 ist beim Versuch Module mit benötigten Ordnerrechten zu installieren ein Fehler aufgetreten (betraf z.B. das Veranstaltungen- und Teams-Modul).  
- Karrusssell in der "Modul Info"-Ansicht war ohne Funktion.  
- Kleinere Fehlerbehebungen und Verbesserungen.  
 **Veranstaltungen-Modules (1.23.5):**  
- Fehler beim Installieren behoben.
**Teams-Modules (1.24.4):**  
- Fehler beim Installieren behoben.  
**Wie halte ich Ilch auf den aktuellen Stand?**  
<a href="https://github.com/IlchCMS/Ilch-2.0/wiki/Doku-Benutzer-Ilch-aktuell-halten" target="_blank">Doku Benutzer Ilch aktuell …

fixes und Version

---

application/modules/awards/config/config.php
application/modules/forum/config/config.php
application/modules/linkus/config/config.php
application/modules/partner/config/config.php

- Call drop table with if exists clause.
https://dev.mysql.com/doc/refman/5.7/en/drop-table.html

Module uninstall: Call drop table with if exists clause

---

application/modules/user/controllers/Panel.php

- Use getNotifications. The result from getNotificationsSortedByDateType looked random.

User Panel: Use getNotifications

---

.github/workflows/ci.yaml

Try a different variant of the CI workflow as the previous one triggered a docker limit.
> docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.

Different variant of CI workflow

---

application/modules/events/controllers/Index.php
application/modules/teams/controllers/admin/Index.php

- Revert marginal changes as they don't justify a new versions of the modules.
#1162

Revert marginal changes

---

application/modules/awards/config/config.php
application/modules/forum/config/config.php

- Fix wrong drop table syntax.
#1176

Fix wrong drop table syntax

---

index.php

**Version 2.2.10**
**Dieses Update beinhaltet Sicherheitsverbesserungen. Ein Update wird empfohlen.**
Mit tarteaucitron in Version 1.20.1 wurden drei Sicherheitslücken geschlossen.
Die Upload-Klasse wurde überarbeitet. Mehrere Funktionen und Eigenschaften der Upload-Klasse wurden mit Ilch 2.2.9 als veraltet markiert und nun entfernt. Sollten Sie die Upload-Klasse z.B. in einem ihrer eigenen Module nutzen, sind kleinere Anpassungen bei der Nutzung dieser Klasse nötig. Für Ilch und die offiziellen Module wurden diese Anpassungen bereits vorgenommen. 
[Hinweise für Entwickler](https://github.com/IlchCMS/Ilch-2.0/wiki/Hinweise-f%C3%BCr-Entwickler)
**Änderungen**
Ilch:
* Das "backups"-Verzeichnis kann nun auf Datenbank-Backups durchsucht werden, um diese herunterzuladen oder zu importieren. So …

Betatest 2.2.10

---

application/modules/admin/config/config.php
composer.lock

- Update to Bootstrap 5.3.5
**For after the release of Ilch 2.2.10.**

Update to Bootstrap 5.3.5

---

application/libraries/Ilch/View.php

- Some code style fixes for the view class of the ilch libraries.
Made these little changes while looking at the class related to work on the shop module.
**For after the release of Ilch 2.2.10.**

Libraries: ilch view code style fixes

---

application/modules/calendar/config/config.php

Calendar: Fix wrong path

---

application/modules/shop/controllers/admin/Properties.php

- Fix several errors occurring when creating or editing properties for product variants reported in the forum.
https://www.ilch.de/index.php?forum-showposts-58690-p1#409014

Shop: Fix reported errors dealing with properties

---

application/modules/media/views/admin/ajax/index.php

- Add missing PHP opening tag and if

Media: Add missing PHP opening tag and if

---

application/modules/shop/controllers/admin/Items.php

Shop: Fix "Undefined array key"

---

application/modules/forum/config/config.php
application/modules/forum/views/admin/index/index.php

- Fix editing of categories and forums.
Basically the same issue as fixed by https://github.com/IlchCMS/Ilch-2.0/pull/1199.

Forum: Fix editing of categories and forums

---

application/modules/admin/config/config.php
composer.lock

- Update PHPMailer to version 6.10.0

Update PHPMailer to version 6.10.0

---

application/modules/shop/views/admin/items/treat.php
application/modules/shop/views/index/index.php

- Show note if a product has variants in frontend index view.

Shop: Show note if a product has variants in frontend index view

---

application/modules/shop/controllers/admin/Items.php
application/modules/shop/mappers/Propertyvariants.php
application/modules/shop/translations/de.php
application/modules/shop/translations/en.php
application/modules/shop/views/admin/items/treat.php

- Add hyperlink to parent product.
- Further some smaller code improvements.

Shop: Add hyperlink to parent product

---

build/optimize_build.php

- Keep "emoji-definitions.json"

Update optimize_build.php to keep "emoji-definitions.json"

---

composer.lock

Update Bootstrap to v5.3.6

---

static/js/highlight/highlight.min.js

- Update highlight.js to v11.11.1

Update highlight.js to v11.11.1

---

application/modules/admin/views/admin/infos/logs.php
application/modules/admin/views/admin/settings/maintenance.php
application/modules/article/views/admin/index/treat.php
application/modules/cookieconsent/views/admin/index/index.php
static/css/ilch.css

- Remove first batch of ilch-date usage
- Remove ilch-date css class.
#1232

Remove first batch of ilch-date usage

---

application/modules/admin/config/config.php
index.php

Remove second updateserver
